dependencies:
# build
  - python >=3.8
  - numpy >=1.16
  - ipopt >=1.13
  - swig
  - meson >=0.46
  - compilers
  - pkg-config
  - libpgmath   # [win]
  - pip
  - setuptools
  - build
# testing
  - parameterized
  - testflo
  - scipy >1.2
  - mdolab-baseclasses >=1.3.1
  - sqlitedict >=1.6