C     -*- fortran -*-
C     This file is autogenerated with f2py (version:2)
C     It contains Fortran 77 wrappers to fortran functions.

      subroutine f2pyinitoutput(setupfunc)
      external setupfunc
      integer iout
      common /output/ iout
      call setupfunc(iout)
      end

      subroutine f2pyinitvarable(setupfunc)
      external setupfunc
      double precision aobj
      common /varable/ aobj
      call setupfunc(aobj)
      end

      subroutine f2pyinitcnmn1(setupfunc)
      external setupfunc
      double precision delfun
      double precision dabfun
      double precision fdch
      double precision fdchm
      double precision ct
      double precision ctmin
      double precision ctl
      double precision ctlmin
      double precision alphax
      double precision abobj1
      double precision theta
      double precision obj
      integer ndv
      integer ncon
      integer nside
      integer iprint
      integer nfdg
      integer nscal
      integer linobj
      integer itmax
      integer itrm
      integer icndir
      integer igoto
      integer nac
      integer info
      integer infog
      integer iter
      common /cnmn1/ delfun,dabfun,fdch,fdchm,ct,ctmin,ctl,ctlmin,
     &alphax,abobj1,theta,obj,ndv,ncon,nside,iprint,nfdg,nscal,linobj,it
     &max,itrm,icndir,igoto,nac,info,infog,iter
      call setupfunc(delfun,dabfun,fdch,fdchm,ct,ctmin,ctl,ctlmin,
     &alphax,abobj1,theta,obj,ndv,ncon,nside,iprint,nfdg,nscal,linobj,it
     &max,itrm,icndir,igoto,nac,info,infog,iter)
      end


