/* File: conminmodule.c
 * This file is auto-generated with f2py (version:2).
 * f2py is a Fortran to Python Interface Generator (FPIG), Second Edition,
 * written by Pearu Peterson <pearu@cens.ioc.ee>.
 * See http://cens.ioc.ee/projects/f2py2e/
 * Generation date: Mon Sep  7 14:26:48 2015
 * $Revision:$
 * $Date:$
 * Do not edit this file directly unless you know what you are doing!!!
 */
#ifdef __cplusplus
extern "C" {
#endif

/*********************** See f2py2e/cfuncs.py: includes ***********************/
#include "Python.h"
#include <stdarg.h>
#include "fortranobject.h"
#include <string.h>
#include <setjmp.h>

/**************** See f2py2e/rules.py: mod_rules['modulebody'] ****************/
static PyObject *conmin_error;
static PyObject *conmin_module;

/*********************** See f2py2e/cfuncs.py: typedefs ***********************/
typedef char * string;
typedef signed char signed_char;

/****************** See f2py2e/cfuncs.py: typedefs_generated ******************/
typedef void(*cb_cnmngrd_in_conmin__user__routines_typedef)(int *,int *,double *,double *,double *,double *,double *,double *,int *,int *);
typedef void(*cb_cnmnfun_in_conmin__user__routines_typedef)(int *,int *,double *,double *,double *);

/********************** See f2py2e/cfuncs.py: cppmacros **********************/
#define STRINGMALLOC(str,len)\
  if ((str = (string)malloc(sizeof(char)*(len+1))) == NULL) {\
    PyErr_SetString(PyExc_MemoryError, "out of memory");\
    goto capi_fail;\
  } else {\
    (str)[len] = '\0';\
  }

#ifndef max
#define max(a,b) ((a > b) ? (a) : (b))
#endif
#ifndef min
#define min(a,b) ((a < b) ? (a) : (b))
#endif
#ifndef MAX
#define MAX(a,b) ((a > b) ? (a) : (b))
#endif
#ifndef MIN
#define MIN(a,b) ((a < b) ? (a) : (b))
#endif

#define PRINTPYOBJERR(obj)\
  fprintf(stderr,"conmin.error is related to ");\
  PyObject_Print((PyObject *)obj,stderr,Py_PRINT_RAW);\
  fprintf(stderr,"\n");

\
#define FAILNULL(p) do {                                            \
    if ((p) == NULL) {                                              \
        PyErr_SetString(PyExc_MemoryError, "NULL pointer found");   \
        goto capi_fail;                                             \
    }                                                               \
} while (0)

#define pyobj_from_int1(v) (PyInt_FromLong(v))
#define GETSCALARFROMPYTUPLE(tuple,index,var,ctype,mess) {\
    if ((capi_tmp = PyTuple_GetItem((tuple),(index)))==NULL) goto capi_fail;\
    if (!(ctype ## _from_pyobj((var),capi_tmp,mess)))\
      goto capi_fail;\
  }

#define pyobj_from_double1(v) (PyFloat_FromDouble(v))
#define MEMCOPY(to,from,n)\
    do { FAILNULL(to); FAILNULL(from); (void)memcpy(to,from,n); } while (0)

#ifdef DEBUGCFUNCS
#define CFUNCSMESS(mess) fprintf(stderr,"debug-capi:"mess);
#define CFUNCSMESSPY(mess,obj) CFUNCSMESS(mess) \
  PyObject_Print((PyObject *)obj,stderr,Py_PRINT_RAW);\
  fprintf(stderr,"\n");
#else
#define CFUNCSMESS(mess)
#define CFUNCSMESSPY(mess,obj)
#endif

#if defined(PREPEND_FORTRAN)
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) _##F
#else
#define F_FUNC(f,F) _##f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) _##F##_
#else
#define F_FUNC(f,F) _##f##_
#endif
#endif
#else
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) F
#else
#define F_FUNC(f,F) f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) F##_
#else
#define F_FUNC(f,F) f##_
#endif
#endif
#endif
#if defined(UNDERSCORE_G77)
#define F_FUNC_US(f,F) F_FUNC(f##_,F##_)
#else
#define F_FUNC_US(f,F) F_FUNC(f,F)
#endif

#define rank(var) var ## _Rank
#define shape(var,dim) var ## _Dims[dim]
#define old_rank(var) (((PyArrayObject *)(capi_ ## var ## _tmp))->nd)
#define old_shape(var,dim) (((PyArrayObject *)(capi_ ## var ## _tmp))->dimensions[dim])
#define fshape(var,dim) shape(var,rank(var)-dim-1)
#define len(var) shape(var,0)
#define flen(var) fshape(var,0)
#define old_size(var) PyArray_SIZE((PyArrayObject *)(capi_ ## var ## _tmp))
/* #define index(i) capi_i ## i */
#define slen(var) capi_ ## var ## _len
#define size(var, ...) f2py_size((PyArrayObject *)(capi_ ## var ## _tmp), ## __VA_ARGS__, -1)

#define SWAP(a,b,t) {\
  t *c;\
  c = a;\
  a = b;\
  b = c;}

#define STRINGFREE(str) do {if (!(str == NULL)) free(str);} while (0)

#define STRINGCOPYN(to,from,buf_size)                           \
    do {                                                        \
        int _m = (buf_size);                                    \
        char *_to = (to);                                       \
        char *_from = (from);                                   \
        FAILNULL(_to); FAILNULL(_from);                         \
        (void)strncpy(_to, _from, sizeof(char)*_m);             \
        _to[_m-1] = '\0';                                      \
        /* Padding with spaces instead of nulls */              \
        for (_m -= 2; _m >= 0 && _to[_m] == '\0'; _m--) {      \
            _to[_m] = ' ';                                      \
        }                                                       \
    } while (0)

/* New SciPy */
#define TRYPYARRAYTEMPLATECHAR case NPY_STRING: *(char *)(arr->data)=*v; break;
#define TRYPYARRAYTEMPLATELONG case NPY_LONG: *(long *)(arr->data)=*v; break;
#define TRYPYARRAYTEMPLATEOBJECT case NPY_OBJECT: (arr->descr->f->setitem)(pyobj_from_ ## ctype ## 1(*v),arr->data); break;

#define TRYPYARRAYTEMPLATE(ctype,typecode) \
        PyArrayObject *arr = NULL;\
        if (!obj) return -2;\
        if (!PyArray_Check(obj)) return -1;\
        if (!(arr=(PyArrayObject *)obj)) {fprintf(stderr,"TRYPYARRAYTEMPLATE:");PRINTPYOBJERR(obj);return 0;}\
        if (arr->descr->type==typecode)  {*(ctype *)(arr->data)=*v; return 1;}\
        switch (arr->descr->type_num) {\
                case NPY_DOUBLE: *(double *)(arr->data)=*v; break;\
                case NPY_INT: *(int *)(arr->data)=*v; break;\
                case NPY_LONG: *(long *)(arr->data)=*v; break;\
                case NPY_FLOAT: *(float *)(arr->data)=*v; break;\
                case NPY_CDOUBLE: *(double *)(arr->data)=*v; break;\
                case NPY_CFLOAT: *(float *)(arr->data)=*v; break;\
                case NPY_BOOL: *(npy_bool *)(arr->data)=(*v!=0); break;\
                case NPY_UBYTE: *(unsigned char *)(arr->data)=*v; break;\
                case NPY_BYTE: *(signed char *)(arr->data)=*v; break;\
                case NPY_SHORT: *(short *)(arr->data)=*v; break;\
                case NPY_USHORT: *(npy_ushort *)(arr->data)=*v; break;\
                case NPY_UINT: *(npy_uint *)(arr->data)=*v; break;\
                case NPY_ULONG: *(npy_ulong *)(arr->data)=*v; break;\
                case NPY_LONGLONG: *(npy_longlong *)(arr->data)=*v; break;\
                case NPY_ULONGLONG: *(npy_ulonglong *)(arr->data)=*v; break;\
                case NPY_LONGDOUBLE: *(npy_longdouble *)(arr->data)=*v; break;\
                case NPY_CLONGDOUBLE: *(npy_longdouble *)(arr->data)=*v; break;\
                case NPY_OBJECT: (arr->descr->f->setitem)(pyobj_from_ ## ctype ## 1(*v),arr->data, arr); break;\
        default: return -2;\
        };\
        return 1


/************************ See f2py2e/cfuncs.py: cfuncs ************************/
static int f2py_size(PyArrayObject* var, ...)
{
  npy_int sz = 0;
  npy_int dim;
  npy_int rank;
  va_list argp;
  va_start(argp, var);
  dim = va_arg(argp, npy_int);
  if (dim==-1)
    {
      sz = PyArray_SIZE(var);
    }
  else
    {
      rank = PyArray_NDIM(var);
      if (dim>=1 && dim<=rank)
        sz = PyArray_DIM(var, dim-1);
      else
        fprintf(stderr, "f2py_size: 2nd argument value=%d fails to satisfy 1<=value<=%d. Result will be 0.\n", dim, rank);
    }
  va_end(argp);
  return sz;
}

static int double_from_pyobj(double* v,PyObject *obj,const char *errmess) {
  PyObject* tmp = NULL;
  if (PyFloat_Check(obj)) {
#ifdef __sgi
    *v = PyFloat_AsDouble(obj);
#else
    *v = PyFloat_AS_DOUBLE(obj);
#endif
    return 1;
  }
  tmp = PyNumber_Float(obj);
  if (tmp) {
#ifdef __sgi
    *v = PyFloat_AsDouble(tmp);
#else
    *v = PyFloat_AS_DOUBLE(tmp);
#endif
    Py_DECREF(tmp);
    return 1;
  }
  if (PyComplex_Check(obj))
    tmp = PyObject_GetAttrString(obj,"real");
  else if (PyString_Check(obj) || PyUnicode_Check(obj))
    /*pass*/;
  else if (PySequence_Check(obj))
    tmp = PySequence_GetItem(obj,0);
  if (tmp) {
    PyErr_Clear();
    if (double_from_pyobj(v,tmp,errmess)) {Py_DECREF(tmp); return 1;}
    Py_DECREF(tmp);
  }
  {
    PyObject* err = PyErr_Occurred();
    if (err==NULL) err = conmin_error;
    PyErr_SetString(err,errmess);
  }
  return 0;
}

static int int_from_pyobj(int* v,PyObject *obj,const char *errmess) {
  PyObject* tmp = NULL;
  if (PyInt_Check(obj)) {
    *v = (int)PyInt_AS_LONG(obj);
    return 1;
  }
  tmp = PyNumber_Int(obj);
  if (tmp) {
    *v = PyInt_AS_LONG(tmp);
    Py_DECREF(tmp);
    return 1;
  }
  if (PyComplex_Check(obj))
    tmp = PyObject_GetAttrString(obj,"real");
  else if (PyString_Check(obj) || PyUnicode_Check(obj))
    /*pass*/;
  else if (PySequence_Check(obj))
    tmp = PySequence_GetItem(obj,0);
  if (tmp) {
    PyErr_Clear();
    if (int_from_pyobj(v,tmp,errmess)) {Py_DECREF(tmp); return 1;}
    Py_DECREF(tmp);
  }
  {
    PyObject* err = PyErr_Occurred();
    if (err==NULL) err = conmin_error;
    PyErr_SetString(err,errmess);
  }
  return 0;
}

static int try_pyarr_from_double(PyObject* obj,double* v) {
  TRYPYARRAYTEMPLATE(double,'d');
}

static int try_pyarr_from_int(PyObject* obj,int* v) {
  TRYPYARRAYTEMPLATE(int,'i');
}

static int create_cb_arglist(PyObject* fun,PyTupleObject* xa,const int maxnofargs,const int nofoptargs,int *nofargs,PyTupleObject **args,const char *errmess) {
  PyObject *tmp = NULL;
  PyObject *tmp_fun = NULL;
  int tot,opt,ext,siz,i,di=0;
  CFUNCSMESS("create_cb_arglist\n");
  tot=opt=ext=siz=0;
  /* Get the total number of arguments */
  if (PyFunction_Check(fun))
    tmp_fun = fun;
  else {
    di = 1;
    if (PyObject_HasAttrString(fun,"im_func")) {
      tmp_fun = PyObject_GetAttrString(fun,"im_func");
    }
    else if (PyObject_HasAttrString(fun,"__call__")) {
      tmp = PyObject_GetAttrString(fun,"__call__");
      if (PyObject_HasAttrString(tmp,"im_func"))
        tmp_fun = PyObject_GetAttrString(tmp,"im_func");
      else {
        tmp_fun = fun; /* built-in function */
        tot = maxnofargs;
        if (xa != NULL)
          tot += PyTuple_Size((PyObject *)xa);
      }
      Py_XDECREF(tmp);
    }
    else if (PyFortran_Check(fun) || PyFortran_Check1(fun)) {
      tot = maxnofargs;
      if (xa != NULL)
        tot += PyTuple_Size((PyObject *)xa);
      tmp_fun = fun;
    }
    else if (F2PyCapsule_Check(fun)) {
      tot = maxnofargs;
      if (xa != NULL)
        ext = PyTuple_Size((PyObject *)xa);
      if(ext>0) {
        fprintf(stderr,"extra arguments tuple cannot be used with CObject call-back\n");
        goto capi_fail;
      }
      tmp_fun = fun;
    }
  }
if (tmp_fun==NULL) {
fprintf(stderr,"Call-back argument must be function|instance|instance.__call__|f2py-function but got %s.\n",(fun==NULL?"NULL":Py_TYPE(fun)->tp_name));
goto capi_fail;
}
#if PY_VERSION_HEX >= 0x03000000
  if (PyObject_HasAttrString(tmp_fun,"__code__")) {
    if (PyObject_HasAttrString(tmp = PyObject_GetAttrString(tmp_fun,"__code__"),"co_argcount"))
#else
  if (PyObject_HasAttrString(tmp_fun,"func_code")) {
    if (PyObject_HasAttrString(tmp = PyObject_GetAttrString(tmp_fun,"func_code"),"co_argcount"))
#endif
      tot = PyInt_AsLong(PyObject_GetAttrString(tmp,"co_argcount")) - di;
    Py_XDECREF(tmp);
  }
  /* Get the number of optional arguments */
#if PY_VERSION_HEX >= 0x03000000
  if (PyObject_HasAttrString(tmp_fun,"__defaults__")) {
    if (PyTuple_Check(tmp = PyObject_GetAttrString(tmp_fun,"__defaults__")))
#else
  if (PyObject_HasAttrString(tmp_fun,"func_defaults")) {
    if (PyTuple_Check(tmp = PyObject_GetAttrString(tmp_fun,"func_defaults")))
#endif
      opt = PyTuple_Size(tmp);
    Py_XDECREF(tmp);
  }
  /* Get the number of extra arguments */
  if (xa != NULL)
    ext = PyTuple_Size((PyObject *)xa);
  /* Calculate the size of call-backs argument list */
  siz = MIN(maxnofargs+ext,tot);
  *nofargs = MAX(0,siz-ext);
#ifdef DEBUGCFUNCS
  fprintf(stderr,"debug-capi:create_cb_arglist:maxnofargs(-nofoptargs),tot,opt,ext,siz,nofargs=%d(-%d),%d,%d,%d,%d,%d\n",maxnofargs,nofoptargs,tot,opt,ext,siz,*nofargs);
#endif
  if (siz<tot-opt) {
    fprintf(stderr,"create_cb_arglist: Failed to build argument list (siz) with enough arguments (tot-opt) required by user-supplied function (siz,tot,opt=%d,%d,%d).\n",siz,tot,opt);
    goto capi_fail;
  }
  /* Initialize argument list */
  *args = (PyTupleObject *)PyTuple_New(siz);
  for (i=0;i<*nofargs;i++) {
    Py_INCREF(Py_None);
    PyTuple_SET_ITEM((PyObject *)(*args),i,Py_None);
  }
  if (xa != NULL)
    for (i=(*nofargs);i<siz;i++) {
      tmp = PyTuple_GetItem((PyObject *)xa,i-(*nofargs));
      Py_INCREF(tmp);
      PyTuple_SET_ITEM(*args,i,tmp);
    }
  CFUNCSMESS("create_cb_arglist-end\n");
  return 1;
capi_fail:
  if ((PyErr_Occurred())==NULL)
    PyErr_SetString(conmin_error,errmess);
  return 0;
}

static int string_from_pyobj(string *str,int *len,const string inistr,PyObject *obj,const char *errmess) {
  PyArrayObject *arr = NULL;
  PyObject *tmp = NULL;
#ifdef DEBUGCFUNCS
fprintf(stderr,"string_from_pyobj(str='%s',len=%d,inistr='%s',obj=%p)\n",(char*)str,*len,(char *)inistr,obj);
#endif
  if (obj == Py_None) {
    if (*len == -1)
      *len = strlen(inistr); /* Will this cause problems? */
    STRINGMALLOC(*str,*len);
    STRINGCOPYN(*str,inistr,*len+1);
    return 1;
  }
  if (PyArray_Check(obj)) {
    if ((arr = (PyArrayObject *)obj) == NULL)
      goto capi_fail;
    if (!ISCONTIGUOUS(arr)) {
      PyErr_SetString(PyExc_ValueError,"array object is non-contiguous.");
      goto capi_fail;
    }
    if (*len == -1)
      *len = (arr->descr->elsize)*PyArray_SIZE(arr);
    STRINGMALLOC(*str,*len);
    STRINGCOPYN(*str,arr->data,*len+1);
    return 1;
  }
  if (PyString_Check(obj)) {
    tmp = obj;
    Py_INCREF(tmp);
  }
#if PY_VERSION_HEX >= 0x03000000
  else if (PyUnicode_Check(obj)) {
    tmp = PyUnicode_AsASCIIString(obj);
  }
  else {
    PyObject *tmp2;
    tmp2 = PyObject_Str(obj);
    if (tmp2) {
      tmp = PyUnicode_AsASCIIString(tmp2);
      Py_DECREF(tmp2);
    }
    else {
      tmp = NULL;
    }
  }
#else
  else {
    tmp = PyObject_Str(obj);
  }
#endif
  if (tmp == NULL) goto capi_fail;
  if (*len == -1)
    *len = PyString_GET_SIZE(tmp);
  STRINGMALLOC(*str,*len);
  STRINGCOPYN(*str,PyString_AS_STRING(tmp),*len+1);
  Py_DECREF(tmp);
  return 1;
capi_fail:
  Py_XDECREF(tmp);
  {
    PyObject* err = PyErr_Occurred();
    if (err==NULL) err = conmin_error;
    PyErr_SetString(err,errmess);
  }
  return 0;
}


/********************* See f2py2e/cfuncs.py: userincludes *********************/
/*need_userincludes*/

/********************* See f2py2e/capi_rules.py: usercode *********************/


/* See f2py2e/rules.py */
extern void F_FUNC(conmin,CONMIN)(int*,int*,double*,double*,double*,double*,double*,int*,int*,int*,int*,int*,int*,int*,string,int*,double*,double*,int*,int*,int*,int*,int*,cb_cnmnfun_in_conmin__user__routines_typedef,cb_cnmngrd_in_conmin__user__routines_typedef,size_t);
extern void F_FUNC(openunit,OPENUNIT)(int*,string,string,string,int*,size_t,size_t,size_t);
extern void F_FUNC(pyflush,PYFLUSH)(int*);
extern void F_FUNC(closeunit,CLOSEUNIT)(int*);
/*eof externroutines*/

/******************** See f2py2e/capi_rules.py: usercode1 ********************/


/******************* See f2py2e/cb_rules.py: buildcallback *******************/

/******************** cb_cnmnfun_in_conmin__user__routines ********************/
PyObject *cb_cnmnfun_in_conmin__user__routines_capi = NULL;/*was Py_None*/
PyTupleObject *cb_cnmnfun_in_conmin__user__routines_args_capi = NULL;
int cb_cnmnfun_in_conmin__user__routines_nofargs = 0;
jmp_buf cb_cnmnfun_in_conmin__user__routines_jmpbuf;
/*typedef void(*cb_cnmnfun_in_conmin__user__routines_typedef)(int *,int *,double *,double *,double *);*/
static void cb_cnmnfun_in_conmin__user__routines (int *n1_cb_capi,int *n2_cb_capi,double *x,double *aobj_cb_capi,double *g) {
  PyTupleObject *capi_arglist = cb_cnmnfun_in_conmin__user__routines_args_capi;
  PyObject *capi_return = NULL;
  PyObject *capi_tmp = NULL;
  int capi_j,capi_i = 0;
  int capi_longjmp_ok = 1;
/*decl*/
  int n1=(*n1_cb_capi);
  int n2=(*n2_cb_capi);
  double aobj=(*aobj_cb_capi);
  npy_intp g_Dims[1] = {-1};
  npy_intp x_Dims[1] = {-1};
#ifdef F2PY_REPORT_ATEXIT
f2py_cb_start_clock();
#endif
  CFUNCSMESS("cb:Call-back function cb_cnmnfun_in_conmin__user__routines (maxnofargs=5(-0))\n");
  CFUNCSMESSPY("cb:cb_cnmnfun_in_conmin__user__routines_capi=",cb_cnmnfun_in_conmin__user__routines_capi);
  if (cb_cnmnfun_in_conmin__user__routines_capi==NULL) {
    capi_longjmp_ok = 0;
    cb_cnmnfun_in_conmin__user__routines_capi = PyObject_GetAttrString(conmin_module,"cnmnfun");
  }
  if (cb_cnmnfun_in_conmin__user__routines_capi==NULL) {
    PyErr_SetString(conmin_error,"cb: Callback cnmnfun not defined (as an argument or module conmin attribute).\n");
    goto capi_fail;
  }
  if (F2PyCapsule_Check(cb_cnmnfun_in_conmin__user__routines_capi)) {
  cb_cnmnfun_in_conmin__user__routines_typedef cb_cnmnfun_in_conmin__user__routines_cptr;
  cb_cnmnfun_in_conmin__user__routines_cptr = F2PyCapsule_AsVoidPtr(cb_cnmnfun_in_conmin__user__routines_capi);
  (*cb_cnmnfun_in_conmin__user__routines_cptr)(n1_cb_capi,n2_cb_capi,x,aobj_cb_capi,g);
  return;
  }
  if (capi_arglist==NULL) {
    capi_longjmp_ok = 0;
    capi_tmp = PyObject_GetAttrString(conmin_module,"cnmnfun_extra_args");
    if (capi_tmp) {
      capi_arglist = (PyTupleObject *)PySequence_Tuple(capi_tmp);
      if (capi_arglist==NULL) {
        PyErr_SetString(conmin_error,"Failed to convert conmin.cnmnfun_extra_args to tuple.\n");
        goto capi_fail;
      }
    } else {
      PyErr_Clear();
      capi_arglist = (PyTupleObject *)Py_BuildValue("()");
    }
  }
  if (capi_arglist == NULL) {
    PyErr_SetString(conmin_error,"Callback cnmnfun argument list is not set.\n");
    goto capi_fail;
  }
/*setdims*/
  g_Dims[0]=n2;
  x_Dims[0]=n1;
/*pyobjfrom*/
  if (cb_cnmnfun_in_conmin__user__routines_nofargs>capi_i)
    if (PyTuple_SetItem((PyObject *)capi_arglist,capi_i++,pyobj_from_int1(n1)))
      goto capi_fail;
  if (cb_cnmnfun_in_conmin__user__routines_nofargs>capi_i)
    if (PyTuple_SetItem((PyObject *)capi_arglist,capi_i++,pyobj_from_int1(n2)))
      goto capi_fail;
  if (cb_cnmnfun_in_conmin__user__routines_nofargs>capi_i) {
    PyArrayObject *tmp_arr = (PyArrayObject *)PyArray_New(&PyArray_Type,1,x_Dims,NPY_DOUBLE,NULL,(char*)x,0,NPY_FARRAY,NULL); /*XXX: Hmm, what will destroy this array??? */


    if (tmp_arr==NULL)
      goto capi_fail;
    if (PyTuple_SetItem((PyObject *)capi_arglist,capi_i++,(PyObject *)tmp_arr))
      goto capi_fail;
}
  if (cb_cnmnfun_in_conmin__user__routines_nofargs>capi_i)
    if (PyTuple_SetItem((PyObject *)capi_arglist,capi_i++,pyobj_from_double1(aobj)))
      goto capi_fail;
  if (cb_cnmnfun_in_conmin__user__routines_nofargs>capi_i) {
    PyArrayObject *tmp_arr = (PyArrayObject *)PyArray_New(&PyArray_Type,1,g_Dims,NPY_DOUBLE,NULL,(char*)g,0,NPY_FARRAY,NULL); /*XXX: Hmm, what will destroy this array??? */


    if (tmp_arr==NULL)
      goto capi_fail;
    if (PyTuple_SetItem((PyObject *)capi_arglist,capi_i++,(PyObject *)tmp_arr))
      goto capi_fail;
}
  CFUNCSMESSPY("cb:capi_arglist=",capi_arglist);
  CFUNCSMESS("cb:Call-back calling Python function cnmnfun.\n");
#ifdef F2PY_REPORT_ATEXIT
f2py_cb_start_call_clock();
#endif
  capi_return = PyObject_CallObject(cb_cnmnfun_in_conmin__user__routines_capi,(PyObject *)capi_arglist);
#ifdef F2PY_REPORT_ATEXIT
f2py_cb_stop_call_clock();
#endif
  CFUNCSMESSPY("cb:capi_return=",capi_return);
  if (capi_return == NULL) {
    fprintf(stderr,"capi_return is NULL\n");
    goto capi_fail;
  }
  if (capi_return == Py_None) {
    Py_DECREF(capi_return);
    capi_return = Py_BuildValue("()");
  }
  else if (!PyTuple_Check(capi_return)) {
    capi_return = Py_BuildValue("(N)",capi_return);
  }
  capi_j = PyTuple_Size(capi_return);
  capi_i = 0;
/*frompyobj*/
  if (capi_j>capi_i)
    GETSCALARFROMPYTUPLE(capi_return,capi_i++,aobj_cb_capi,double,"double_from_pyobj failed in converting argument aobj of call-back function cb_cnmnfun_in_conmin__user__routines to C double\n");
  if (capi_j>capi_i) {
    PyArrayObject *rv_cb_arr = NULL;
    if ((capi_tmp = PyTuple_GetItem(capi_return,capi_i++))==NULL) goto capi_fail;
    rv_cb_arr =  array_from_pyobj(NPY_DOUBLE,g_Dims,1,F2PY_INTENT_IN
,capi_tmp);
    if (rv_cb_arr == NULL) {
      fprintf(stderr,"rv_cb_arr is NULL\n");
      goto capi_fail;
    }
    MEMCOPY(g,rv_cb_arr->data,PyArray_NBYTES(rv_cb_arr));
    if (capi_tmp != (PyObject *)rv_cb_arr) {
      Py_DECREF(rv_cb_arr);
    }
  }
  CFUNCSMESS("cb:cb_cnmnfun_in_conmin__user__routines:successful\n");
  Py_DECREF(capi_return);
#ifdef F2PY_REPORT_ATEXIT
f2py_cb_stop_clock();
#endif
  goto capi_return_pt;
capi_fail:
  fprintf(stderr,"Call-back cb_cnmnfun_in_conmin__user__routines failed.\n");
  Py_XDECREF(capi_return);
  if (capi_longjmp_ok)
    longjmp(cb_cnmnfun_in_conmin__user__routines_jmpbuf,-1);
capi_return_pt:
  ;
return;
}
/**************** end of cb_cnmnfun_in_conmin__user__routines ****************/


/******************** cb_cnmngrd_in_conmin__user__routines ********************/
PyObject *cb_cnmngrd_in_conmin__user__routines_capi = NULL;/*was Py_None*/
PyTupleObject *cb_cnmngrd_in_conmin__user__routines_args_capi = NULL;
int cb_cnmngrd_in_conmin__user__routines_nofargs = 0;
jmp_buf cb_cnmngrd_in_conmin__user__routines_jmpbuf;
/*typedef void(*cb_cnmngrd_in_conmin__user__routines_typedef)(int *,int *,double *,double *,double *,double *,double *,double *,int *,int *);*/
static void cb_cnmngrd_in_conmin__user__routines (int *n1_cb_capi,int *n2_cb_capi,double *x,double *aobj_cb_capi,double *g,double *ct_cb_capi,double *df,double *a,int *ic,int *nac_cb_capi) {
  PyTupleObject *capi_arglist = cb_cnmngrd_in_conmin__user__routines_args_capi;
  PyObject *capi_return = NULL;
  PyObject *capi_tmp = NULL;
  int capi_j,capi_i = 0;
  int capi_longjmp_ok = 1;
/*decl*/
  int n1=(*n1_cb_capi);
  int n2=(*n2_cb_capi);
  double aobj=(*aobj_cb_capi);
  double ct=(*ct_cb_capi);
  int nac=(*nac_cb_capi);
  npy_intp a_Dims[2] = {-1, -1};
  npy_intp g_Dims[1] = {-1};
  npy_intp df_Dims[1] = {-1};
  npy_intp x_Dims[1] = {-1};
  npy_intp ic_Dims[1] = {-1};
#ifdef F2PY_REPORT_ATEXIT
f2py_cb_start_clock();
#endif
  CFUNCSMESS("cb:Call-back function cb_cnmngrd_in_conmin__user__routines (maxnofargs=10(-0))\n");
  CFUNCSMESSPY("cb:cb_cnmngrd_in_conmin__user__routines_capi=",cb_cnmngrd_in_conmin__user__routines_capi);
  if (cb_cnmngrd_in_conmin__user__routines_capi==NULL) {
    capi_longjmp_ok = 0;
    cb_cnmngrd_in_conmin__user__routines_capi = PyObject_GetAttrString(conmin_module,"cnmngrd");
  }
  if (cb_cnmngrd_in_conmin__user__routines_capi==NULL) {
    PyErr_SetString(conmin_error,"cb: Callback cnmngrd not defined (as an argument or module conmin attribute).\n");
    goto capi_fail;
  }
  if (F2PyCapsule_Check(cb_cnmngrd_in_conmin__user__routines_capi)) {
  cb_cnmngrd_in_conmin__user__routines_typedef cb_cnmngrd_in_conmin__user__routines_cptr;
  cb_cnmngrd_in_conmin__user__routines_cptr = F2PyCapsule_AsVoidPtr(cb_cnmngrd_in_conmin__user__routines_capi);
  (*cb_cnmngrd_in_conmin__user__routines_cptr)(n1_cb_capi,n2_cb_capi,x,aobj_cb_capi,g,ct_cb_capi,df,a,ic,nac_cb_capi);
  return;
  }
  if (capi_arglist==NULL) {
    capi_longjmp_ok = 0;
    capi_tmp = PyObject_GetAttrString(conmin_module,"cnmngrd_extra_args");
    if (capi_tmp) {
      capi_arglist = (PyTupleObject *)PySequence_Tuple(capi_tmp);
      if (capi_arglist==NULL) {
        PyErr_SetString(conmin_error,"Failed to convert conmin.cnmngrd_extra_args to tuple.\n");
        goto capi_fail;
      }
    } else {
      PyErr_Clear();
      capi_arglist = (PyTupleObject *)Py_BuildValue("()");
    }
  }
  if (capi_arglist == NULL) {
    PyErr_SetString(conmin_error,"Callback cnmngrd argument list is not set.\n");
    goto capi_fail;
  }
/*setdims*/
  a_Dims[0]=n1,a_Dims[1]=n2;
  g_Dims[0]=n2;
  df_Dims[0]=n1;
  x_Dims[0]=n1;
  ic_Dims[0]=n2;
/*pyobjfrom*/
  if (cb_cnmngrd_in_conmin__user__routines_nofargs>capi_i)
    if (PyTuple_SetItem((PyObject *)capi_arglist,capi_i++,pyobj_from_int1(n1)))
      goto capi_fail;
  if (cb_cnmngrd_in_conmin__user__routines_nofargs>capi_i)
    if (PyTuple_SetItem((PyObject *)capi_arglist,capi_i++,pyobj_from_int1(n2)))
      goto capi_fail;
  if (cb_cnmngrd_in_conmin__user__routines_nofargs>capi_i) {
    PyArrayObject *tmp_arr = (PyArrayObject *)PyArray_New(&PyArray_Type,1,x_Dims,NPY_DOUBLE,NULL,(char*)x,0,NPY_FARRAY,NULL); /*XXX: Hmm, what will destroy this array??? */


    if (tmp_arr==NULL)
      goto capi_fail;
    if (PyTuple_SetItem((PyObject *)capi_arglist,capi_i++,(PyObject *)tmp_arr))
      goto capi_fail;
}
  if (cb_cnmngrd_in_conmin__user__routines_nofargs>capi_i)
    if (PyTuple_SetItem((PyObject *)capi_arglist,capi_i++,pyobj_from_double1(aobj)))
      goto capi_fail;
  if (cb_cnmngrd_in_conmin__user__routines_nofargs>capi_i) {
    PyArrayObject *tmp_arr = (PyArrayObject *)PyArray_New(&PyArray_Type,1,g_Dims,NPY_DOUBLE,NULL,(char*)g,0,NPY_FARRAY,NULL); /*XXX: Hmm, what will destroy this array??? */


    if (tmp_arr==NULL)
      goto capi_fail;
    if (PyTuple_SetItem((PyObject *)capi_arglist,capi_i++,(PyObject *)tmp_arr))
      goto capi_fail;
}
  if (cb_cnmngrd_in_conmin__user__routines_nofargs>capi_i)
    if (PyTuple_SetItem((PyObject *)capi_arglist,capi_i++,pyobj_from_double1(ct)))
      goto capi_fail;
  if (cb_cnmngrd_in_conmin__user__routines_nofargs>capi_i) {
    PyArrayObject *tmp_arr = (PyArrayObject *)PyArray_New(&PyArray_Type,1,df_Dims,NPY_DOUBLE,NULL,(char*)df,0,NPY_FARRAY,NULL); /*XXX: Hmm, what will destroy this array??? */


    if (tmp_arr==NULL)
      goto capi_fail;
    if (PyTuple_SetItem((PyObject *)capi_arglist,capi_i++,(PyObject *)tmp_arr))
      goto capi_fail;
}
  if (cb_cnmngrd_in_conmin__user__routines_nofargs>capi_i) {
    PyArrayObject *tmp_arr = (PyArrayObject *)PyArray_New(&PyArray_Type,2,a_Dims,NPY_DOUBLE,NULL,(char*)a,0,NPY_FARRAY,NULL); /*XXX: Hmm, what will destroy this array??? */


    if (tmp_arr==NULL)
      goto capi_fail;
    if (PyTuple_SetItem((PyObject *)capi_arglist,capi_i++,(PyObject *)tmp_arr))
      goto capi_fail;
}
  if (cb_cnmngrd_in_conmin__user__routines_nofargs>capi_i) {
    PyArrayObject *tmp_arr = (PyArrayObject *)PyArray_New(&PyArray_Type,1,ic_Dims,NPY_INT,NULL,(char*)ic,0,NPY_FARRAY,NULL); /*XXX: Hmm, what will destroy this array??? */


    if (tmp_arr==NULL)
      goto capi_fail;
    if (PyTuple_SetItem((PyObject *)capi_arglist,capi_i++,(PyObject *)tmp_arr))
      goto capi_fail;
}
  if (cb_cnmngrd_in_conmin__user__routines_nofargs>capi_i)
    if (PyTuple_SetItem((PyObject *)capi_arglist,capi_i++,pyobj_from_int1(nac)))
      goto capi_fail;
  CFUNCSMESSPY("cb:capi_arglist=",capi_arglist);
  CFUNCSMESS("cb:Call-back calling Python function cnmngrd.\n");
#ifdef F2PY_REPORT_ATEXIT
f2py_cb_start_call_clock();
#endif
  capi_return = PyObject_CallObject(cb_cnmngrd_in_conmin__user__routines_capi,(PyObject *)capi_arglist);
#ifdef F2PY_REPORT_ATEXIT
f2py_cb_stop_call_clock();
#endif
  CFUNCSMESSPY("cb:capi_return=",capi_return);
  if (capi_return == NULL) {
    fprintf(stderr,"capi_return is NULL\n");
    goto capi_fail;
  }
  if (capi_return == Py_None) {
    Py_DECREF(capi_return);
    capi_return = Py_BuildValue("()");
  }
  else if (!PyTuple_Check(capi_return)) {
    capi_return = Py_BuildValue("(N)",capi_return);
  }
  capi_j = PyTuple_Size(capi_return);
  capi_i = 0;
/*frompyobj*/
  if (capi_j>capi_i) {
    PyArrayObject *rv_cb_arr = NULL;
    if ((capi_tmp = PyTuple_GetItem(capi_return,capi_i++))==NULL) goto capi_fail;
    rv_cb_arr =  array_from_pyobj(NPY_DOUBLE,df_Dims,1,F2PY_INTENT_IN
,capi_tmp);
    if (rv_cb_arr == NULL) {
      fprintf(stderr,"rv_cb_arr is NULL\n");
      goto capi_fail;
    }
    MEMCOPY(df,rv_cb_arr->data,PyArray_NBYTES(rv_cb_arr));
    if (capi_tmp != (PyObject *)rv_cb_arr) {
      Py_DECREF(rv_cb_arr);
    }
  }
  if (capi_j>capi_i) {
    PyArrayObject *rv_cb_arr = NULL;
    if ((capi_tmp = PyTuple_GetItem(capi_return,capi_i++))==NULL) goto capi_fail;
    rv_cb_arr =  array_from_pyobj(NPY_DOUBLE,a_Dims,2,F2PY_INTENT_IN
,capi_tmp);
    if (rv_cb_arr == NULL) {
      fprintf(stderr,"rv_cb_arr is NULL\n");
      goto capi_fail;
    }
    MEMCOPY(a,rv_cb_arr->data,PyArray_NBYTES(rv_cb_arr));
    if (capi_tmp != (PyObject *)rv_cb_arr) {
      Py_DECREF(rv_cb_arr);
    }
  }
  if (capi_j>capi_i) {
    PyArrayObject *rv_cb_arr = NULL;
    if ((capi_tmp = PyTuple_GetItem(capi_return,capi_i++))==NULL) goto capi_fail;
    rv_cb_arr =  array_from_pyobj(NPY_INT,ic_Dims,1,F2PY_INTENT_IN
,capi_tmp);
    if (rv_cb_arr == NULL) {
      fprintf(stderr,"rv_cb_arr is NULL\n");
      goto capi_fail;
    }
    MEMCOPY(ic,rv_cb_arr->data,PyArray_NBYTES(rv_cb_arr));
    if (capi_tmp != (PyObject *)rv_cb_arr) {
      Py_DECREF(rv_cb_arr);
    }
  }
  if (capi_j>capi_i)
    GETSCALARFROMPYTUPLE(capi_return,capi_i++,nac_cb_capi,int,"int_from_pyobj failed in converting argument nac of call-back function cb_cnmngrd_in_conmin__user__routines to C int\n");
  CFUNCSMESS("cb:cb_cnmngrd_in_conmin__user__routines:successful\n");
  Py_DECREF(capi_return);
#ifdef F2PY_REPORT_ATEXIT
f2py_cb_stop_clock();
#endif
  goto capi_return_pt;
capi_fail:
  fprintf(stderr,"Call-back cb_cnmngrd_in_conmin__user__routines failed.\n");
  Py_XDECREF(capi_return);
  if (capi_longjmp_ok)
    longjmp(cb_cnmngrd_in_conmin__user__routines_jmpbuf,-1);
capi_return_pt:
  ;
return;
}
/**************** end of cb_cnmngrd_in_conmin__user__routines ****************/


/*********************** See f2py2e/rules.py: buildapi ***********************/

/*********************************** conmin ***********************************/
static char doc_f2py_rout_conmin_conmin[] = "\
conmin(ndv_,ncon_,x_,vlb_,vub_,obj_,g_,n1,n2,n3,n4,n5,iprint_,iout_,ifile,itmax_,delfun_,dabfun_,itrm_,nfeasct_,nfdg_,nfun_,ngrd_,cnmnfun,cnmngrd,[cnmnfun_extra_args,cnmngrd_extra_args])\n\nWrapper for ``conmin``.\
\n\nParameters\n----------\n"
"ndv_ : input int\n"
"ncon_ : input int\n"
"x_ : in/output rank-1 array('d') with bounds (ndv_)\n"
"vlb_ : input rank-1 array('d') with bounds (ndv_)\n"
"vub_ : input rank-1 array('d') with bounds (ndv_)\n"
"obj_ : in/output rank-0 array(float,'d')\n"
"g_ : in/output rank-1 array('d') with bounds (ncon_)\n"
"n1 : input int\n"
"n2 : input int\n"
"n3 : input int\n"
"n4 : input int\n"
"n5 : input int\n"
"iprint_ : input int\n"
"iout_ : input int\n"
"ifile : input string(len=-1)\n"
"itmax_ : input int\n"
"delfun_ : input float\n"
"dabfun_ : input float\n"
"itrm_ : input int\n"
"nfeasct_ : input int\n"
"nfdg_ : input int\n"
"nfun_ : in/output rank-0 array(int,'i')\n"
"ngrd_ : in/output rank-0 array(int,'i')\n"
"cnmnfun : call-back function\n"
"cnmngrd : call-back function\n"
"\nOther Parameters\n----------------\n"
"cnmnfun_extra_args : input tuple, optional\n    Default: ()\n"
"cnmngrd_extra_args : input tuple, optional\n    Default: ()\n"
"\nNotes\n-----\nCall-back functions::\n\n"
"  def cnmnfun(n1,n2,x,aobj,g): return aobj,g\n\
  Required arguments:\n"
"    n1 : input int\n"
"    n2 : input int\n"
"    x : input rank-1 array('d') with bounds (n1)\n"
"    aobj : input float\n"
"    g : input rank-1 array('d') with bounds (n2)\n"
"  Return objects:\n"
"    aobj : float\n"
"    g : rank-1 array('d') with bounds (n2)\n"
"  def cnmngrd(n1,n2,x,aobj,g,ct,df,a,ic,nac): return df,a,ic,nac\n\
  Required arguments:\n"
"    n1 : input int\n"
"    n2 : input int\n"
"    x : input rank-1 array('d') with bounds (n1)\n"
"    aobj : input float\n"
"    g : input rank-1 array('d') with bounds (n2)\n"
"    ct : input float\n"
"    df : input rank-1 array('d') with bounds (n1)\n"
"    a : input rank-2 array('d') with bounds (n1,n2)\n"
"    ic : input rank-1 array('i') with bounds (n2)\n"
"    nac : input int\n"
"  Return objects:\n"
"    df : rank-1 array('d') with bounds (n1)\n"
"    a : rank-2 array('d') with bounds (n1,n2)\n"
"    ic : rank-1 array('i') with bounds (n2)\n"
"    nac : int";
/* extern void F_FUNC(conmin,CONMIN)(int*,int*,double*,double*,double*,double*,double*,int*,int*,int*,int*,int*,int*,int*,string,int*,double*,double*,int*,int*,int*,int*,int*,cb_cnmnfun_in_conmin__user__routines_typedef,cb_cnmngrd_in_conmin__user__routines_typedef,size_t); */
static PyObject *f2py_rout_conmin_conmin(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*,int*,double*,double*,double*,double*,double*,int*,int*,int*,int*,int*,int*,int*,string,int*,double*,double*,int*,int*,int*,int*,int*,cb_cnmnfun_in_conmin__user__routines_typedef,cb_cnmngrd_in_conmin__user__routines_typedef,size_t)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  int ndv_ = 0;
  PyObject *ndv__capi = Py_None;
  int ncon_ = 0;
  PyObject *ncon__capi = Py_None;
  double *x_ = NULL;
  npy_intp x__Dims[1] = {-1};
  const int x__Rank = 1;
  PyArrayObject *capi_x__tmp = NULL;
  int capi_x__intent = 0;
  PyObject *x__capi = Py_None;
  double *vlb_ = NULL;
  npy_intp vlb__Dims[1] = {-1};
  const int vlb__Rank = 1;
  PyArrayObject *capi_vlb__tmp = NULL;
  int capi_vlb__intent = 0;
  PyObject *vlb__capi = Py_None;
  double *vub_ = NULL;
  npy_intp vub__Dims[1] = {-1};
  const int vub__Rank = 1;
  PyArrayObject *capi_vub__tmp = NULL;
  int capi_vub__intent = 0;
  PyObject *vub__capi = Py_None;
  double obj_ = 0;
  PyObject *obj__capi = Py_None;
  double *g_ = NULL;
  npy_intp g__Dims[1] = {-1};
  const int g__Rank = 1;
  PyArrayObject *capi_g__tmp = NULL;
  int capi_g__intent = 0;
  PyObject *g__capi = Py_None;
  int n1 = 0;
  PyObject *n1_capi = Py_None;
  int n2 = 0;
  PyObject *n2_capi = Py_None;
  int n3 = 0;
  PyObject *n3_capi = Py_None;
  int n4 = 0;
  PyObject *n4_capi = Py_None;
  int n5 = 0;
  PyObject *n5_capi = Py_None;
  int iprint_ = 0;
  PyObject *iprint__capi = Py_None;
  int iout_ = 0;
  PyObject *iout__capi = Py_None;
  string ifile = NULL;
  int slen(ifile);
  PyObject *ifile_capi = Py_None;
  int itmax_ = 0;
  PyObject *itmax__capi = Py_None;
  double delfun_ = 0;
  PyObject *delfun__capi = Py_None;
  double dabfun_ = 0;
  PyObject *dabfun__capi = Py_None;
  int itrm_ = 0;
  PyObject *itrm__capi = Py_None;
  int nfeasct_ = 0;
  PyObject *nfeasct__capi = Py_None;
  int nfdg_ = 0;
  PyObject *nfdg__capi = Py_None;
  int nfun_ = 0;
  PyObject *nfun__capi = Py_None;
  int ngrd_ = 0;
  PyObject *ngrd__capi = Py_None;
  PyObject *cnmnfun_capi = Py_None;
  PyTupleObject *cnmnfun_xa_capi = NULL;
  PyTupleObject *cnmnfun_args_capi = NULL;
  int cnmnfun_nofargs_capi = 0;
  cb_cnmnfun_in_conmin__user__routines_typedef cnmnfun_cptr;
  PyObject *cnmngrd_capi = Py_None;
  PyTupleObject *cnmngrd_xa_capi = NULL;
  PyTupleObject *cnmngrd_args_capi = NULL;
  int cnmngrd_nofargs_capi = 0;
  cb_cnmngrd_in_conmin__user__routines_typedef cnmngrd_cptr;
  static char *capi_kwlist[] = {"ndv_","ncon_","x_","vlb_","vub_","obj_","g_","n1","n2","n3","n4","n5","iprint_","iout_","ifile","itmax_","delfun_","dabfun_","itrm_","nfeasct_","nfdg_","nfun_","ngrd_","cnmnfun","cnmngrd","cnmnfun_extra_args","cnmngrd_extra_args",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOOOOOOOOOOOOOOOOOOOOOOOO|O!O!:conmin.conmin",\
    capi_kwlist,&ndv__capi,&ncon__capi,&x__capi,&vlb__capi,&vub__capi,&obj__capi,&g__capi,&n1_capi,&n2_capi,&n3_capi,&n4_capi,&n5_capi,&iprint__capi,&iout__capi,&ifile_capi,&itmax__capi,&delfun__capi,&dabfun__capi,&itrm__capi,&nfeasct__capi,&nfdg__capi,&nfun__capi,&ngrd__capi,&cnmnfun_capi,&cnmngrd_capi,&PyTuple_Type,&cnmnfun_xa_capi,&PyTuple_Type,&cnmngrd_xa_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable delfun_ */
    f2py_success = double_from_pyobj(&delfun_,delfun__capi,"conmin.conmin() 17th argument (delfun_) can't be converted to double");
  if (f2py_success) {
  /* Processing variable itrm_ */
    f2py_success = int_from_pyobj(&itrm_,itrm__capi,"conmin.conmin() 19th argument (itrm_) can't be converted to int");
  if (f2py_success) {
  /* Processing variable nfeasct_ */
    f2py_success = int_from_pyobj(&nfeasct_,nfeasct__capi,"conmin.conmin() 20th argument (nfeasct_) can't be converted to int");
  if (f2py_success) {
  /* Processing variable cnmnfun */
if(F2PyCapsule_Check(cnmnfun_capi)) {
  cnmnfun_cptr = F2PyCapsule_AsVoidPtr(cnmnfun_capi);
} else {
  cnmnfun_cptr = cb_cnmnfun_in_conmin__user__routines;
}

  cnmnfun_nofargs_capi = cb_cnmnfun_in_conmin__user__routines_nofargs;
  if (create_cb_arglist(cnmnfun_capi,cnmnfun_xa_capi,5,0,&cb_cnmnfun_in_conmin__user__routines_nofargs,&cnmnfun_args_capi,"failed in processing argument list for call-back cnmnfun.")) {
    jmp_buf cnmnfun_jmpbuf;
    CFUNCSMESS("Saving jmpbuf for `cnmnfun`.\n");
    SWAP(cnmnfun_capi,cb_cnmnfun_in_conmin__user__routines_capi,PyObject);
    SWAP(cnmnfun_args_capi,cb_cnmnfun_in_conmin__user__routines_args_capi,PyTupleObject);
    memcpy(&cnmnfun_jmpbuf,&cb_cnmnfun_in_conmin__user__routines_jmpbuf,sizeof(jmp_buf));
  /* Processing variable dabfun_ */
    f2py_success = double_from_pyobj(&dabfun_,dabfun__capi,"conmin.conmin() 18th argument (dabfun_) can't be converted to double");
  if (f2py_success) {
  /* Processing variable obj_ */
    f2py_success = double_from_pyobj(&obj_,obj__capi,"conmin.conmin() 6th argument (obj_) can't be converted to double");
  if (f2py_success) {
  /* Processing variable ifile */
  slen(ifile) = -1;
  f2py_success = string_from_pyobj(&ifile,&slen(ifile),"",ifile_capi,"string_from_pyobj failed in converting 15th argument `ifile' of conmin.conmin to C string");
  if (f2py_success) {
  /* Processing variable cnmngrd */
if(F2PyCapsule_Check(cnmngrd_capi)) {
  cnmngrd_cptr = F2PyCapsule_AsVoidPtr(cnmngrd_capi);
} else {
  cnmngrd_cptr = cb_cnmngrd_in_conmin__user__routines;
}

  cnmngrd_nofargs_capi = cb_cnmngrd_in_conmin__user__routines_nofargs;
  if (create_cb_arglist(cnmngrd_capi,cnmngrd_xa_capi,10,0,&cb_cnmngrd_in_conmin__user__routines_nofargs,&cnmngrd_args_capi,"failed in processing argument list for call-back cnmngrd.")) {
    jmp_buf cnmngrd_jmpbuf;
    CFUNCSMESS("Saving jmpbuf for `cnmngrd`.\n");
    SWAP(cnmngrd_capi,cb_cnmngrd_in_conmin__user__routines_capi,PyObject);
    SWAP(cnmngrd_args_capi,cb_cnmngrd_in_conmin__user__routines_args_capi,PyTupleObject);
    memcpy(&cnmngrd_jmpbuf,&cb_cnmngrd_in_conmin__user__routines_jmpbuf,sizeof(jmp_buf));
  /* Processing variable ngrd_ */
    f2py_success = int_from_pyobj(&ngrd_,ngrd__capi,"conmin.conmin() 23rd argument (ngrd_) can't be converted to int");
  if (f2py_success) {
  /* Processing variable ndv_ */
    f2py_success = int_from_pyobj(&ndv_,ndv__capi,"conmin.conmin() 1st argument (ndv_) can't be converted to int");
  if (f2py_success) {
  /* Processing variable itmax_ */
    f2py_success = int_from_pyobj(&itmax_,itmax__capi,"conmin.conmin() 16th argument (itmax_) can't be converted to int");
  if (f2py_success) {
  /* Processing variable nfdg_ */
    f2py_success = int_from_pyobj(&nfdg_,nfdg__capi,"conmin.conmin() 21st argument (nfdg_) can't be converted to int");
  if (f2py_success) {
  /* Processing variable iout_ */
    f2py_success = int_from_pyobj(&iout_,iout__capi,"conmin.conmin() 14th argument (iout_) can't be converted to int");
  if (f2py_success) {
  /* Processing variable nfun_ */
    f2py_success = int_from_pyobj(&nfun_,nfun__capi,"conmin.conmin() 22nd argument (nfun_) can't be converted to int");
  if (f2py_success) {
  /* Processing variable ncon_ */
    f2py_success = int_from_pyobj(&ncon_,ncon__capi,"conmin.conmin() 2nd argument (ncon_) can't be converted to int");
  if (f2py_success) {
  /* Processing variable iprint_ */
    f2py_success = int_from_pyobj(&iprint_,iprint__capi,"conmin.conmin() 13rd argument (iprint_) can't be converted to int");
  if (f2py_success) {
  /* Processing variable n1 */
    f2py_success = int_from_pyobj(&n1,n1_capi,"conmin.conmin() 8th argument (n1) can't be converted to int");
  if (f2py_success) {
  /* Processing variable n2 */
    f2py_success = int_from_pyobj(&n2,n2_capi,"conmin.conmin() 9th argument (n2) can't be converted to int");
  if (f2py_success) {
  /* Processing variable n3 */
    f2py_success = int_from_pyobj(&n3,n3_capi,"conmin.conmin() 10th argument (n3) can't be converted to int");
  if (f2py_success) {
  /* Processing variable n4 */
    f2py_success = int_from_pyobj(&n4,n4_capi,"conmin.conmin() 11st argument (n4) can't be converted to int");
  if (f2py_success) {
  /* Processing variable n5 */
    f2py_success = int_from_pyobj(&n5,n5_capi,"conmin.conmin() 12nd argument (n5) can't be converted to int");
  if (f2py_success) {
  /* Processing variable vlb_ */
  vlb__Dims[0]=ndv_;
  capi_vlb__intent |= F2PY_INTENT_IN;
  capi_vlb__tmp = array_from_pyobj(NPY_DOUBLE,vlb__Dims,vlb__Rank,capi_vlb__intent,vlb__capi);
  if (capi_vlb__tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(conmin_error,"failed in converting 4th argument `vlb_' of conmin.conmin to C/Fortran array" );
  } else {
    vlb_ = (double *)(capi_vlb__tmp->data);

  /* Processing variable g_ */
  g__Dims[0]=ncon_;
  capi_g__intent |= F2PY_INTENT_INOUT;
  capi_g__tmp = array_from_pyobj(NPY_DOUBLE,g__Dims,g__Rank,capi_g__intent,g__capi);
  if (capi_g__tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(conmin_error,"failed in converting 7th argument `g_' of conmin.conmin to C/Fortran array" );
  } else {
    g_ = (double *)(capi_g__tmp->data);

  /* Processing variable vub_ */
  vub__Dims[0]=ndv_;
  capi_vub__intent |= F2PY_INTENT_IN;
  capi_vub__tmp = array_from_pyobj(NPY_DOUBLE,vub__Dims,vub__Rank,capi_vub__intent,vub__capi);
  if (capi_vub__tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(conmin_error,"failed in converting 5th argument `vub_' of conmin.conmin to C/Fortran array" );
  } else {
    vub_ = (double *)(capi_vub__tmp->data);

  /* Processing variable x_ */
  x__Dims[0]=ndv_;
  capi_x__intent |= F2PY_INTENT_INOUT;
  capi_x__tmp = array_from_pyobj(NPY_DOUBLE,x__Dims,x__Rank,capi_x__intent,x__capi);
  if (capi_x__tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(conmin_error,"failed in converting 3rd argument `x_' of conmin.conmin to C/Fortran array" );
  } else {
    x_ = (double *)(capi_x__tmp->data);

/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
    if ((setjmp(cb_cnmnfun_in_conmin__user__routines_jmpbuf)) || (setjmp(cb_cnmngrd_in_conmin__user__routines_jmpbuf))) {
      f2py_success = 0;
    } else {
        (*f2py_func)(&ndv_,&ncon_,x_,vlb_,vub_,&obj_,g_,&n1,&n2,&n3,&n4,&n5,&iprint_,&iout_,ifile,&itmax_,&delfun_,&dabfun_,&itrm_,&nfeasct_,&nfdg_,&nfun_,&ngrd_,cnmnfun_cptr,cnmngrd_cptr,slen(ifile));
    }
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
  f2py_success = try_pyarr_from_double(obj__capi,&obj_);
  if (f2py_success) {
  f2py_success = try_pyarr_from_int(nfun__capi,&nfun_);
  if (f2py_success) {
  f2py_success = try_pyarr_from_int(ngrd__capi,&ngrd_);
  if (f2py_success) {
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("");
/*closepyobjfrom*/
  } /*if (f2py_success) of ngrd_ pyobjfrom*/
  } /*if (f2py_success) of nfun_ pyobjfrom*/
  } /*if (f2py_success) of obj_ pyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  if((PyObject *)capi_x__tmp!=x__capi) {
    Py_XDECREF(capi_x__tmp); }
  }  /*if (capi_x__tmp == NULL) ... else of x_*/
  /* End of cleaning variable x_ */
  if((PyObject *)capi_vub__tmp!=vub__capi) {
    Py_XDECREF(capi_vub__tmp); }
  }  /*if (capi_vub__tmp == NULL) ... else of vub_*/
  /* End of cleaning variable vub_ */
  if((PyObject *)capi_g__tmp!=g__capi) {
    Py_XDECREF(capi_g__tmp); }
  }  /*if (capi_g__tmp == NULL) ... else of g_*/
  /* End of cleaning variable g_ */
  if((PyObject *)capi_vlb__tmp!=vlb__capi) {
    Py_XDECREF(capi_vlb__tmp); }
  }  /*if (capi_vlb__tmp == NULL) ... else of vlb_*/
  /* End of cleaning variable vlb_ */
  } /*if (f2py_success) of n5*/
  /* End of cleaning variable n5 */
  } /*if (f2py_success) of n4*/
  /* End of cleaning variable n4 */
  } /*if (f2py_success) of n3*/
  /* End of cleaning variable n3 */
  } /*if (f2py_success) of n2*/
  /* End of cleaning variable n2 */
  } /*if (f2py_success) of n1*/
  /* End of cleaning variable n1 */
  } /*if (f2py_success) of iprint_*/
  /* End of cleaning variable iprint_ */
  } /*if (f2py_success) of ncon_*/
  /* End of cleaning variable ncon_ */
  } /*if (f2py_success) of nfun_*/
  /* End of cleaning variable nfun_ */
  } /*if (f2py_success) of iout_*/
  /* End of cleaning variable iout_ */
  } /*if (f2py_success) of nfdg_*/
  /* End of cleaning variable nfdg_ */
  } /*if (f2py_success) of itmax_*/
  /* End of cleaning variable itmax_ */
  } /*if (f2py_success) of ndv_*/
  /* End of cleaning variable ndv_ */
  } /*if (f2py_success) of ngrd_*/
  /* End of cleaning variable ngrd_ */
    CFUNCSMESS("Restoring jmpbuf for `cnmngrd`.\n");
    cb_cnmngrd_in_conmin__user__routines_capi = cnmngrd_capi;
    Py_DECREF(cb_cnmngrd_in_conmin__user__routines_args_capi);
    cb_cnmngrd_in_conmin__user__routines_args_capi = cnmngrd_args_capi;
    cb_cnmngrd_in_conmin__user__routines_nofargs = cnmngrd_nofargs_capi;
    memcpy(&cb_cnmngrd_in_conmin__user__routines_jmpbuf,&cnmngrd_jmpbuf,sizeof(jmp_buf));
  }
  /* End of cleaning variable cnmngrd */
    STRINGFREE(ifile);
  }  /*if (f2py_success) of ifile*/
  /* End of cleaning variable ifile */
  } /*if (f2py_success) of obj_*/
  /* End of cleaning variable obj_ */
  } /*if (f2py_success) of dabfun_*/
  /* End of cleaning variable dabfun_ */
    CFUNCSMESS("Restoring jmpbuf for `cnmnfun`.\n");
    cb_cnmnfun_in_conmin__user__routines_capi = cnmnfun_capi;
    Py_DECREF(cb_cnmnfun_in_conmin__user__routines_args_capi);
    cb_cnmnfun_in_conmin__user__routines_args_capi = cnmnfun_args_capi;
    cb_cnmnfun_in_conmin__user__routines_nofargs = cnmnfun_nofargs_capi;
    memcpy(&cb_cnmnfun_in_conmin__user__routines_jmpbuf,&cnmnfun_jmpbuf,sizeof(jmp_buf));
  }
  /* End of cleaning variable cnmnfun */
  } /*if (f2py_success) of nfeasct_*/
  /* End of cleaning variable nfeasct_ */
  } /*if (f2py_success) of itrm_*/
  /* End of cleaning variable itrm_ */
  } /*if (f2py_success) of delfun_*/
  /* End of cleaning variable delfun_ */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/******************************* end of conmin *******************************/

/********************************** openunit **********************************/
static char doc_f2py_rout_conmin_openunit[] = "\
ierror = openunit(unitnum,filename,filestatus,fileaction)\n\nWrapper for ``openunit``.\
\n\nParameters\n----------\n"
"unitnum : input int\n"
"filename : input string(len=-1)\n"
"filestatus : input string(len=-1)\n"
"fileaction : input string(len=-1)\n"
"\nReturns\n-------\n"
"ierror : int";
/* extern void F_FUNC(openunit,OPENUNIT)(int*,string,string,string,int*,size_t,size_t,size_t); */
static PyObject *f2py_rout_conmin_openunit(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*,string,string,string,int*,size_t,size_t,size_t)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  int unitnum = 0;
  PyObject *unitnum_capi = Py_None;
  string filename = NULL;
  int slen(filename);
  PyObject *filename_capi = Py_None;
  string filestatus = NULL;
  int slen(filestatus);
  PyObject *filestatus_capi = Py_None;
  string fileaction = NULL;
  int slen(fileaction);
  PyObject *fileaction_capi = Py_None;
  int ierror = 0;
  static char *capi_kwlist[] = {"unitnum","filename","filestatus","fileaction",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOOO:conmin.openunit",\
    capi_kwlist,&unitnum_capi,&filename_capi,&filestatus_capi,&fileaction_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable filestatus */
  slen(filestatus) = -1;
  f2py_success = string_from_pyobj(&filestatus,&slen(filestatus),"",filestatus_capi,"string_from_pyobj failed in converting 3rd argument `filestatus' of conmin.openunit to C string");
  if (f2py_success) {
  /* Processing variable filename */
  slen(filename) = -1;
  f2py_success = string_from_pyobj(&filename,&slen(filename),"",filename_capi,"string_from_pyobj failed in converting 2nd argument `filename' of conmin.openunit to C string");
  if (f2py_success) {
  /* Processing variable unitnum */
    f2py_success = int_from_pyobj(&unitnum,unitnum_capi,"conmin.openunit() 1st argument (unitnum) can't be converted to int");
  if (f2py_success) {
  /* Processing variable fileaction */
  slen(fileaction) = -1;
  f2py_success = string_from_pyobj(&fileaction,&slen(fileaction),"",fileaction_capi,"string_from_pyobj failed in converting 4th argument `fileaction' of conmin.openunit to C string");
  if (f2py_success) {
  /* Processing variable ierror */
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(&unitnum,filename,filestatus,fileaction,&ierror,slen(filename),slen(filestatus),slen(fileaction));
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("i",ierror);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  /* End of cleaning variable ierror */
    STRINGFREE(fileaction);
  }  /*if (f2py_success) of fileaction*/
  /* End of cleaning variable fileaction */
  } /*if (f2py_success) of unitnum*/
  /* End of cleaning variable unitnum */
    STRINGFREE(filename);
  }  /*if (f2py_success) of filename*/
  /* End of cleaning variable filename */
    STRINGFREE(filestatus);
  }  /*if (f2py_success) of filestatus*/
  /* End of cleaning variable filestatus */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/****************************** end of openunit ******************************/

/********************************** pyflush **********************************/
static char doc_f2py_rout_conmin_pyflush[] = "\
pyflush(unitnum)\n\nWrapper for ``pyflush``.\
\n\nParameters\n----------\n"
"unitnum : input int";
/* extern void F_FUNC(pyflush,PYFLUSH)(int*); */
static PyObject *f2py_rout_conmin_pyflush(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  int unitnum = 0;
  PyObject *unitnum_capi = Py_None;
  static char *capi_kwlist[] = {"unitnum",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "O:conmin.pyflush",\
    capi_kwlist,&unitnum_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable unitnum */
    f2py_success = int_from_pyobj(&unitnum,unitnum_capi,"conmin.pyflush() 1st argument (unitnum) can't be converted to int");
  if (f2py_success) {
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(&unitnum);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("");
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  } /*if (f2py_success) of unitnum*/
  /* End of cleaning variable unitnum */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/******************************* end of pyflush *******************************/

/********************************* closeunit *********************************/
static char doc_f2py_rout_conmin_closeunit[] = "\
closeunit(unitnum)\n\nWrapper for ``closeunit``.\
\n\nParameters\n----------\n"
"unitnum : input int";
/* extern void F_FUNC(closeunit,CLOSEUNIT)(int*); */
static PyObject *f2py_rout_conmin_closeunit(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  int unitnum = 0;
  PyObject *unitnum_capi = Py_None;
  static char *capi_kwlist[] = {"unitnum",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "O:conmin.closeunit",\
    capi_kwlist,&unitnum_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable unitnum */
    f2py_success = int_from_pyobj(&unitnum,unitnum_capi,"conmin.closeunit() 1st argument (unitnum) can't be converted to int");
  if (f2py_success) {
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(&unitnum);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("");
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  } /*if (f2py_success) of unitnum*/
  /* End of cleaning variable unitnum */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/****************************** end of closeunit ******************************/
/*eof body*/

/******************* See f2py2e/f90mod_rules.py: buildhooks *******************/
/*need_f90modhooks*/

/************** See f2py2e/rules.py: module_rules['modulebody'] **************/

/******************* See f2py2e/common_rules.py: buildhooks *******************/

static FortranDataDef f2py_output_def[] = {
  {"iout",0,{{-1}},NPY_INT},
  {NULL}
};
static void f2py_setup_output(char *iout) {
  int i_f2py=0;
  f2py_output_def[i_f2py++].data = iout;
}
extern void F_FUNC(f2pyinitoutput,F2PYINITOUTPUT)(void(*)(char*));
static void f2py_init_output(void) {
  F_FUNC(f2pyinitoutput,F2PYINITOUTPUT)(f2py_setup_output);
}

static FortranDataDef f2py_varable_def[] = {
  {"aobj",0,{{-1}},NPY_DOUBLE},
  {NULL}
};
static void f2py_setup_varable(char *aobj) {
  int i_f2py=0;
  f2py_varable_def[i_f2py++].data = aobj;
}
extern void F_FUNC(f2pyinitvarable,F2PYINITVARABLE)(void(*)(char*));
static void f2py_init_varable(void) {
  F_FUNC(f2pyinitvarable,F2PYINITVARABLE)(f2py_setup_varable);
}

static FortranDataDef f2py_cnmn1_def[] = {
  {"delfun",0,{{-1}},NPY_DOUBLE},
  {"dabfun",0,{{-1}},NPY_DOUBLE},
  {"fdch",0,{{-1}},NPY_DOUBLE},
  {"fdchm",0,{{-1}},NPY_DOUBLE},
  {"ct",0,{{-1}},NPY_DOUBLE},
  {"ctmin",0,{{-1}},NPY_DOUBLE},
  {"ctl",0,{{-1}},NPY_DOUBLE},
  {"ctlmin",0,{{-1}},NPY_DOUBLE},
  {"alphax",0,{{-1}},NPY_DOUBLE},
  {"abobj1",0,{{-1}},NPY_DOUBLE},
  {"theta",0,{{-1}},NPY_DOUBLE},
  {"obj",0,{{-1}},NPY_DOUBLE},
  {"ndv",0,{{-1}},NPY_INT},
  {"ncon",0,{{-1}},NPY_INT},
  {"nside",0,{{-1}},NPY_INT},
  {"iprint",0,{{-1}},NPY_INT},
  {"nfdg",0,{{-1}},NPY_INT},
  {"nscal",0,{{-1}},NPY_INT},
  {"linobj",0,{{-1}},NPY_INT},
  {"itmax",0,{{-1}},NPY_INT},
  {"itrm",0,{{-1}},NPY_INT},
  {"icndir",0,{{-1}},NPY_INT},
  {"igoto",0,{{-1}},NPY_INT},
  {"nac",0,{{-1}},NPY_INT},
  {"info",0,{{-1}},NPY_INT},
  {"infog",0,{{-1}},NPY_INT},
  {"iter",0,{{-1}},NPY_INT},
  {NULL}
};
static void f2py_setup_cnmn1(char *delfun,char *dabfun,char *fdch,char *fdchm,char *ct,char *ctmin,char *ctl,char *ctlmin,char *alphax,char *abobj1,char *theta,char *obj,char *ndv,char *ncon,char *nside,char *iprint,char *nfdg,char *nscal,char *linobj,char *itmax,char *itrm,char *icndir,char *igoto,char *nac,char *info,char *infog,char *iter) {
  int i_f2py=0;
  f2py_cnmn1_def[i_f2py++].data = delfun;
  f2py_cnmn1_def[i_f2py++].data = dabfun;
  f2py_cnmn1_def[i_f2py++].data = fdch;
  f2py_cnmn1_def[i_f2py++].data = fdchm;
  f2py_cnmn1_def[i_f2py++].data = ct;
  f2py_cnmn1_def[i_f2py++].data = ctmin;
  f2py_cnmn1_def[i_f2py++].data = ctl;
  f2py_cnmn1_def[i_f2py++].data = ctlmin;
  f2py_cnmn1_def[i_f2py++].data = alphax;
  f2py_cnmn1_def[i_f2py++].data = abobj1;
  f2py_cnmn1_def[i_f2py++].data = theta;
  f2py_cnmn1_def[i_f2py++].data = obj;
  f2py_cnmn1_def[i_f2py++].data = ndv;
  f2py_cnmn1_def[i_f2py++].data = ncon;
  f2py_cnmn1_def[i_f2py++].data = nside;
  f2py_cnmn1_def[i_f2py++].data = iprint;
  f2py_cnmn1_def[i_f2py++].data = nfdg;
  f2py_cnmn1_def[i_f2py++].data = nscal;
  f2py_cnmn1_def[i_f2py++].data = linobj;
  f2py_cnmn1_def[i_f2py++].data = itmax;
  f2py_cnmn1_def[i_f2py++].data = itrm;
  f2py_cnmn1_def[i_f2py++].data = icndir;
  f2py_cnmn1_def[i_f2py++].data = igoto;
  f2py_cnmn1_def[i_f2py++].data = nac;
  f2py_cnmn1_def[i_f2py++].data = info;
  f2py_cnmn1_def[i_f2py++].data = infog;
  f2py_cnmn1_def[i_f2py++].data = iter;
}
extern void F_FUNC(f2pyinitcnmn1,F2PYINITCNMN1)(void(*)(char*,char*,char*,char*,char*,char*,char*,char*,char*,char*,char*,char*,char*,char*,char*,char*,char*,char*,char*,char*,char*,char*,char*,char*,char*,char*,char*));
static void f2py_init_cnmn1(void) {
  F_FUNC(f2pyinitcnmn1,F2PYINITCNMN1)(f2py_setup_cnmn1);
}

/*need_commonhooks*/

/**************************** See f2py2e/rules.py ****************************/

static FortranDataDef f2py_routine_defs[] = {
  {"conmin",-1,{{-1}},0,(char *)F_FUNC(conmin,CONMIN),(f2py_init_func)f2py_rout_conmin_conmin,doc_f2py_rout_conmin_conmin},
  {"openunit",-1,{{-1}},0,(char *)F_FUNC(openunit,OPENUNIT),(f2py_init_func)f2py_rout_conmin_openunit,doc_f2py_rout_conmin_openunit},
  {"pyflush",-1,{{-1}},0,(char *)F_FUNC(pyflush,PYFLUSH),(f2py_init_func)f2py_rout_conmin_pyflush,doc_f2py_rout_conmin_pyflush},
  {"closeunit",-1,{{-1}},0,(char *)F_FUNC(closeunit,CLOSEUNIT),(f2py_init_func)f2py_rout_conmin_closeunit,doc_f2py_rout_conmin_closeunit},

/*eof routine_defs*/
  {NULL}
};

static PyMethodDef f2py_module_methods[] = {

  {NULL,NULL}
};

#if PY_VERSION_HEX >= 0x03000000
static struct PyModuleDef moduledef = {
  PyModuleDef_HEAD_INIT,
  "conmin",
  NULL,
  -1,
  f2py_module_methods,
  NULL,
  NULL,
  NULL,
  NULL
};
#endif

#if PY_VERSION_HEX >= 0x03000000
#define RETVAL m
PyMODINIT_FUNC PyInit_conmin(void) {
#else
#define RETVAL
PyMODINIT_FUNC initconmin(void) {
#endif
  int i;
  PyObject *m,*d, *s;
#if PY_VERSION_HEX >= 0x03000000
  m = conmin_module = PyModule_Create(&moduledef);
#else
  m = conmin_module = Py_InitModule("conmin", f2py_module_methods);
#endif
  Py_TYPE(&PyFortran_Type) = &PyType_Type;
  import_array();
  if (PyErr_Occurred())
    {PyErr_SetString(PyExc_ImportError, "can't initialize module conmin (failed to import numpy)"); return RETVAL;}
  d = PyModule_GetDict(m);
  s = PyString_FromString("$Revision: $");
  PyDict_SetItemString(d, "__version__", s);
#if PY_VERSION_HEX >= 0x03000000
  s = PyUnicode_FromString(
#else
  s = PyString_FromString(
#endif
    "This module 'conmin' is auto-generated with f2py (version:2).\nFunctions:\n"
"  conmin(ndv_,ncon_,x_,vlb_,vub_,obj_,g_,n1,n2,n3,n4,n5,iprint_,iout_,ifile,itmax_,delfun_,dabfun_,itrm_,nfeasct_,nfdg_,nfun_,ngrd_,cnmnfun,cnmngrd,cnmnfun_extra_args=(),cnmngrd_extra_args=())\n"
"  ierror = openunit(unitnum,filename,filestatus,fileaction)\n"
"  pyflush(unitnum)\n"
"  closeunit(unitnum)\n"
"COMMON blocks:\n""  /output/ iout\n""  /varable/ aobj\n""  /cnmn1/ delfun,dabfun,fdch,fdchm,ct,ctmin,ctl,ctlmin,alphax,abobj1,theta,obj,ndv,ncon,nside,iprint,nfdg,nscal,linobj,itmax,itrm,icndir,igoto,nac,info,infog,iter\n"".");
  PyDict_SetItemString(d, "__doc__", s);
  conmin_error = PyErr_NewException ("conmin.error", NULL, NULL);
  Py_DECREF(s);
  for(i=0;f2py_routine_defs[i].name!=NULL;i++)
    PyDict_SetItemString(d, f2py_routine_defs[i].name,PyFortranObject_NewAsAttr(&f2py_routine_defs[i]));




/*eof initf2pywraphooks*/
/*eof initf90modhooks*/

  F2PyDict_SetItemString(d, "output", PyFortranObject_New(f2py_output_def,f2py_init_output));
  F2PyDict_SetItemString(d, "varable", PyFortranObject_New(f2py_varable_def,f2py_init_varable));
  F2PyDict_SetItemString(d, "cnmn1", PyFortranObject_New(f2py_cnmn1_def,f2py_init_cnmn1));
/*eof initcommonhooks*/


#ifdef F2PY_REPORT_ATEXIT
  if (! PyErr_Occurred())
    on_exit(f2py_report_on_exit,(void*)"conmin");
#endif

  return RETVAL;
}
#ifdef __cplusplus
}
#endif
