      SUBROUTINE CNMN09(CNMNFUN,CNMNGRD,X,G,IC,DF,A,
     . N1,N2,N3,N4,N5)
      
      IMPLICIT DOUBLE PRECISION(A-H,O-Z)
      
      COMMON /CNMN1/ DELFUN,DABFUN,FDCH,FDCHM,CT,
     .  CTMIN,CTL,CTLMIN,ALPHAX,ABOBJ1,THETA,OBJ,
     .  NDV,NCON,NSIDE,IPRINT,NFDG,NSCAL,LINOBJ,
     .  ITMAX,ITRM,ICNDIR,IGOTO,NAC,INFO,INFOG,ITER
     
      COMMON /VARABLE/ AOBJ
      COMMON /FEVALS/ NFUN,NGRD
      
      DIMENSION X(N1),G(N2),IC(N2),DF(N1),A(N1,N2)
            
      EXTERNAL CNMNFUN,CNMNGRD

C
C
      IF(INFO.GE.2) GO TO 10
C 
C  OBJECTIVE FUNCTION & CONSTRAINTS
C   
      CALL CNMNFUN(N1,N2,X,AOBJ,G)
      NFUN=NFUN+1
      GO TO 20
      
   10 CONTINUE
C
C
C	GRADIENT INFORMATION
C     
      CALL CNMNGRD(N1,N2,X,AOBJ,G,CT,DF,A,IC,NAC)
      NGRD=NGRD+1

   20 CONTINUE
      
      RETURN
      END 
