/* File: slsqpmodule.c
 * This file is auto-generated with f2py (version:2).
 * f2py is a Fortran to Python Interface Generator (FPIG), Second Edition,
 * written by Pearu Peterson <pearu@cens.ioc.ee>.
 * See http://cens.ioc.ee/projects/f2py2e/
 * Generation date: Thu Jan 16 20:14:53 2014
 * $Revision:$
 * $Date:$
 * Do not edit this file directly unless you know what you are doing!!!
 */
#ifdef __cplusplus
extern "C" {
#endif

/*********************** See f2py2e/cfuncs.py: includes ***********************/
#include "Python.h"
#include <stdarg.h>
#include "fortranobject.h"
#include <string.h>
#include <setjmp.h>

/**************** See f2py2e/rules.py: mod_rules['modulebody'] ****************/
static PyObject *slsqp_error;
static PyObject *slsqp_module;

/*********************** See f2py2e/cfuncs.py: typedefs ***********************/
typedef char * string;
typedef signed char signed_char;

/****************** See f2py2e/cfuncs.py: typedefs_generated ******************/
typedef void(*cb_slgrad_in_slsqp__user__routines_typedef)(int *,int *,int *,int *,double *,double *,double *,double *,double *);
typedef void(*cb_slfunc_in_slsqp__user__routines_typedef)(int *,int *,int *,int *,double *,double *,double *);

/********************** See f2py2e/cfuncs.py: cppmacros **********************/
#ifndef max
#define max(a,b) ((a > b) ? (a) : (b))
#endif
#ifndef min
#define min(a,b) ((a < b) ? (a) : (b))
#endif
#ifndef MAX
#define MAX(a,b) ((a > b) ? (a) : (b))
#endif
#ifndef MIN
#define MIN(a,b) ((a < b) ? (a) : (b))
#endif

#define STRINGMALLOC(str,len)\
  if ((str = (string)malloc(sizeof(char)*(len+1))) == NULL) {\
    PyErr_SetString(PyExc_MemoryError, "out of memory");\
    goto capi_fail;\
  } else {\
    (str)[len] = '\0';\
  }

#define PRINTPYOBJERR(obj)\
  fprintf(stderr,"slsqp.error is related to ");\
  PyObject_Print((PyObject *)obj,stderr,Py_PRINT_RAW);\
  fprintf(stderr,"\n");

\
#define FAILNULL(p) do {                                            \
    if ((p) == NULL) {                                              \
        PyErr_SetString(PyExc_MemoryError, "NULL pointer found");   \
        goto capi_fail;                                             \
    }                                                               \
} while (0)

#define pyobj_from_int1(v) (PyInt_FromLong(v))
#define GETSCALARFROMPYTUPLE(tuple,index,var,ctype,mess) {\
    if ((capi_tmp = PyTuple_GetItem((tuple),(index)))==NULL) goto capi_fail;\
    if (!(ctype ## _from_pyobj((var),capi_tmp,mess)))\
      goto capi_fail;\
  }

#define pyobj_from_double1(v) (PyFloat_FromDouble(v))
#define MEMCOPY(to,from,n)\
    do { FAILNULL(to); FAILNULL(from); (void)memcpy(to,from,n); } while (0)

#ifdef DEBUGCFUNCS
#define CFUNCSMESS(mess) fprintf(stderr,"debug-capi:"mess);
#define CFUNCSMESSPY(mess,obj) CFUNCSMESS(mess) \
  PyObject_Print((PyObject *)obj,stderr,Py_PRINT_RAW);\
  fprintf(stderr,"\n");
#else
#define CFUNCSMESS(mess)
#define CFUNCSMESSPY(mess,obj)
#endif

#if defined(PREPEND_FORTRAN)
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) _##F
#else
#define F_FUNC(f,F) _##f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) _##F##_
#else
#define F_FUNC(f,F) _##f##_
#endif
#endif
#else
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) F
#else
#define F_FUNC(f,F) f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) F##_
#else
#define F_FUNC(f,F) f##_
#endif
#endif
#endif
#if defined(UNDERSCORE_G77)
#define F_FUNC_US(f,F) F_FUNC(f##_,F##_)
#else
#define F_FUNC_US(f,F) F_FUNC(f,F)
#endif

#define rank(var) var ## _Rank
#define shape(var,dim) var ## _Dims[dim]
#define old_rank(var) (((PyArrayObject *)(capi_ ## var ## _tmp))->nd)
#define old_shape(var,dim) (((PyArrayObject *)(capi_ ## var ## _tmp))->dimensions[dim])
#define fshape(var,dim) shape(var,rank(var)-dim-1)
#define len(var) shape(var,0)
#define flen(var) fshape(var,0)
#define old_size(var) PyArray_SIZE((PyArrayObject *)(capi_ ## var ## _tmp))
/* #define index(i) capi_i ## i */
#define slen(var) capi_ ## var ## _len
#define size(var, ...) f2py_size((PyArrayObject *)(capi_ ## var ## _tmp), ## __VA_ARGS__, -1)

#define STRINGFREE(str) do {if (!(str == NULL)) free(str);} while (0)

#define SWAP(a,b,t) {\
  t *c;\
  c = a;\
  a = b;\
  b = c;}

#define STRINGCOPYN(to,from,buf_size)                           \
    do {                                                        \
        int _m = (buf_size);                                    \
        char *_to = (to);                                       \
        char *_from = (from);                                   \
        FAILNULL(_to); FAILNULL(_from);                         \
        (void)strncpy(_to, _from, sizeof(char)*_m);             \
        _to[_m-1] = '\0';                                      \
        /* Padding with spaces instead of nulls */              \
        for (_m -= 2; _m >= 0 && _to[_m] == '\0'; _m--) {      \
            _to[_m] = ' ';                                      \
        }                                                       \
    } while (0)

/* New SciPy */
#define TRYPYARRAYTEMPLATECHAR case NPY_STRING: *(char *)(arr->data)=*v; break;
#define TRYPYARRAYTEMPLATELONG case NPY_LONG: *(long *)(arr->data)=*v; break;
#define TRYPYARRAYTEMPLATEOBJECT case NPY_OBJECT: (arr->descr->f->setitem)(pyobj_from_ ## ctype ## 1(*v),arr->data); break;

#define TRYPYARRAYTEMPLATE(ctype,typecode) \
        PyArrayObject *arr = NULL;\
        if (!obj) return -2;\
        if (!PyArray_Check(obj)) return -1;\
        if (!(arr=(PyArrayObject *)obj)) {fprintf(stderr,"TRYPYARRAYTEMPLATE:");PRINTPYOBJERR(obj);return 0;}\
        if (arr->descr->type==typecode)  {*(ctype *)(arr->data)=*v; return 1;}\
        switch (arr->descr->type_num) {\
                case NPY_DOUBLE: *(double *)(arr->data)=*v; break;\
                case NPY_INT: *(int *)(arr->data)=*v; break;\
                case NPY_LONG: *(long *)(arr->data)=*v; break;\
                case NPY_FLOAT: *(float *)(arr->data)=*v; break;\
                case NPY_CDOUBLE: *(double *)(arr->data)=*v; break;\
                case NPY_CFLOAT: *(float *)(arr->data)=*v; break;\
                case NPY_BOOL: *(npy_bool *)(arr->data)=(*v!=0); break;\
                case NPY_UBYTE: *(unsigned char *)(arr->data)=*v; break;\
                case NPY_BYTE: *(signed char *)(arr->data)=*v; break;\
                case NPY_SHORT: *(short *)(arr->data)=*v; break;\
                case NPY_USHORT: *(npy_ushort *)(arr->data)=*v; break;\
                case NPY_UINT: *(npy_uint *)(arr->data)=*v; break;\
                case NPY_ULONG: *(npy_ulong *)(arr->data)=*v; break;\
                case NPY_LONGLONG: *(npy_longlong *)(arr->data)=*v; break;\
                case NPY_ULONGLONG: *(npy_ulonglong *)(arr->data)=*v; break;\
                case NPY_LONGDOUBLE: *(npy_longdouble *)(arr->data)=*v; break;\
                case NPY_CLONGDOUBLE: *(npy_longdouble *)(arr->data)=*v; break;\
                case NPY_OBJECT: (arr->descr->f->setitem)(pyobj_from_ ## ctype ## 1(*v),arr->data, arr); break;\
        default: return -2;\
        };\
        return 1


/************************ See f2py2e/cfuncs.py: cfuncs ************************/
static int f2py_size(PyArrayObject* var, ...)
{
  npy_int sz = 0;
  npy_int dim;
  npy_int rank;
  va_list argp;
  va_start(argp, var);
  dim = va_arg(argp, npy_int);
  if (dim==-1)
    {
      sz = PyArray_SIZE(var);
    }
  else
    {
      rank = PyArray_NDIM(var);
      if (dim>=1 && dim<=rank)
        sz = PyArray_DIM(var, dim-1);
      else
        fprintf(stderr, "f2py_size: 2nd argument value=%d fails to satisfy 1<=value<=%d. Result will be 0.\n", dim, rank);
    }
  va_end(argp);
  return sz;
}

static int double_from_pyobj(double* v,PyObject *obj,const char *errmess) {
  PyObject* tmp = NULL;
  if (PyFloat_Check(obj)) {
#ifdef __sgi
    *v = PyFloat_AsDouble(obj);
#else
    *v = PyFloat_AS_DOUBLE(obj);
#endif
    return 1;
  }
  tmp = PyNumber_Float(obj);
  if (tmp) {
#ifdef __sgi
    *v = PyFloat_AsDouble(tmp);
#else
    *v = PyFloat_AS_DOUBLE(tmp);
#endif
    Py_DECREF(tmp);
    return 1;
  }
  if (PyComplex_Check(obj))
    tmp = PyObject_GetAttrString(obj,"real");
  else if (PyString_Check(obj) || PyUnicode_Check(obj))
    /*pass*/;
  else if (PySequence_Check(obj))
    tmp = PySequence_GetItem(obj,0);
  if (tmp) {
    PyErr_Clear();
    if (double_from_pyobj(v,tmp,errmess)) {Py_DECREF(tmp); return 1;}
    Py_DECREF(tmp);
  }
  {
    PyObject* err = PyErr_Occurred();
    if (err==NULL) err = slsqp_error;
    PyErr_SetString(err,errmess);
  }
  return 0;
}

static int try_pyarr_from_double(PyObject* obj,double* v) {
  TRYPYARRAYTEMPLATE(double,'d');
}

static int try_pyarr_from_int(PyObject* obj,int* v) {
  TRYPYARRAYTEMPLATE(int,'i');
}

static int int_from_pyobj(int* v,PyObject *obj,const char *errmess) {
  PyObject* tmp = NULL;
  if (PyInt_Check(obj)) {
    *v = (int)PyInt_AS_LONG(obj);
    return 1;
  }
  tmp = PyNumber_Int(obj);
  if (tmp) {
    *v = PyInt_AS_LONG(tmp);
    Py_DECREF(tmp);
    return 1;
  }
  if (PyComplex_Check(obj))
    tmp = PyObject_GetAttrString(obj,"real");
  else if (PyString_Check(obj) || PyUnicode_Check(obj))
    /*pass*/;
  else if (PySequence_Check(obj))
    tmp = PySequence_GetItem(obj,0);
  if (tmp) {
    PyErr_Clear();
    if (int_from_pyobj(v,tmp,errmess)) {Py_DECREF(tmp); return 1;}
    Py_DECREF(tmp);
  }
  {
    PyObject* err = PyErr_Occurred();
    if (err==NULL) err = slsqp_error;
    PyErr_SetString(err,errmess);
  }
  return 0;
}

static int string_from_pyobj(string *str,int *len,const string inistr,PyObject *obj,const char *errmess) {
  PyArrayObject *arr = NULL;
  PyObject *tmp = NULL;
#ifdef DEBUGCFUNCS
fprintf(stderr,"string_from_pyobj(str='%s',len=%d,inistr='%s',obj=%p)\n",(char*)str,*len,(char *)inistr,obj);
#endif
  if (obj == Py_None) {
    if (*len == -1)
      *len = strlen(inistr); /* Will this cause problems? */
    STRINGMALLOC(*str,*len);
    STRINGCOPYN(*str,inistr,*len+1);
    return 1;
  }
  if (PyArray_Check(obj)) {
    if ((arr = (PyArrayObject *)obj) == NULL)
      goto capi_fail;
    if (!ISCONTIGUOUS(arr)) {
      PyErr_SetString(PyExc_ValueError,"array object is non-contiguous.");
      goto capi_fail;
    }
    if (*len == -1)
      *len = (arr->descr->elsize)*PyArray_SIZE(arr);
    STRINGMALLOC(*str,*len);
    STRINGCOPYN(*str,arr->data,*len+1);
    return 1;
  }
  if (PyString_Check(obj)) {
    tmp = obj;
    Py_INCREF(tmp);
  }
#if PY_VERSION_HEX >= 0x03000000
  else if (PyUnicode_Check(obj)) {
    tmp = PyUnicode_AsASCIIString(obj);
  }
  else {
    PyObject *tmp2;
    tmp2 = PyObject_Str(obj);
    if (tmp2) {
      tmp = PyUnicode_AsASCIIString(tmp2);
      Py_DECREF(tmp2);
    }
    else {
      tmp = NULL;
    }
  }
#else
  else {
    tmp = PyObject_Str(obj);
  }
#endif
  if (tmp == NULL) goto capi_fail;
  if (*len == -1)
    *len = PyString_GET_SIZE(tmp);
  STRINGMALLOC(*str,*len);
  STRINGCOPYN(*str,PyString_AS_STRING(tmp),*len+1);
  Py_DECREF(tmp);
  return 1;
capi_fail:
  Py_XDECREF(tmp);
  {
    PyObject* err = PyErr_Occurred();
    if (err==NULL) err = slsqp_error;
    PyErr_SetString(err,errmess);
  }
  return 0;
}

static int create_cb_arglist(PyObject* fun,PyTupleObject* xa,const int maxnofargs,const int nofoptargs,int *nofargs,PyTupleObject **args,const char *errmess) {
  PyObject *tmp = NULL;
  PyObject *tmp_fun = NULL;
  int tot,opt,ext,siz,i,di=0;
  CFUNCSMESS("create_cb_arglist\n");
  tot=opt=ext=siz=0;
  /* Get the total number of arguments */
  if (PyFunction_Check(fun))
    tmp_fun = fun;
  else {
    di = 1;
    if (PyObject_HasAttrString(fun,"im_func")) {
      tmp_fun = PyObject_GetAttrString(fun,"im_func");
    }
    else if (PyObject_HasAttrString(fun,"__call__")) {
      tmp = PyObject_GetAttrString(fun,"__call__");
      if (PyObject_HasAttrString(tmp,"im_func"))
        tmp_fun = PyObject_GetAttrString(tmp,"im_func");
      else {
        tmp_fun = fun; /* built-in function */
        tot = maxnofargs;
        if (xa != NULL)
          tot += PyTuple_Size((PyObject *)xa);
      }
      Py_XDECREF(tmp);
    }
    else if (PyFortran_Check(fun) || PyFortran_Check1(fun)) {
      tot = maxnofargs;
      if (xa != NULL)
        tot += PyTuple_Size((PyObject *)xa);
      tmp_fun = fun;
    }
    else if (F2PyCapsule_Check(fun)) {
      tot = maxnofargs;
      if (xa != NULL)
        ext = PyTuple_Size((PyObject *)xa);
      if(ext>0) {
        fprintf(stderr,"extra arguments tuple cannot be used with CObject call-back\n");
        goto capi_fail;
      }
      tmp_fun = fun;
    }
  }
if (tmp_fun==NULL) {
fprintf(stderr,"Call-back argument must be function|instance|instance.__call__|f2py-function but got %s.\n",(fun==NULL?"NULL":Py_TYPE(fun)->tp_name));
goto capi_fail;
}
#if PY_VERSION_HEX >= 0x03000000
  if (PyObject_HasAttrString(tmp_fun,"__code__")) {
    if (PyObject_HasAttrString(tmp = PyObject_GetAttrString(tmp_fun,"__code__"),"co_argcount"))
#else
  if (PyObject_HasAttrString(tmp_fun,"func_code")) {
    if (PyObject_HasAttrString(tmp = PyObject_GetAttrString(tmp_fun,"func_code"),"co_argcount"))
#endif
      tot = PyInt_AsLong(PyObject_GetAttrString(tmp,"co_argcount")) - di;
    Py_XDECREF(tmp);
  }
  /* Get the number of optional arguments */
#if PY_VERSION_HEX >= 0x03000000
  if (PyObject_HasAttrString(tmp_fun,"__defaults__"))
    if (PyTuple_Check(tmp = PyObject_GetAttrString(tmp_fun,"__defaults__")))
#else
  if (PyObject_HasAttrString(tmp_fun,"func_defaults"))
    if (PyTuple_Check(tmp = PyObject_GetAttrString(tmp_fun,"func_defaults")))
#endif
      opt = PyTuple_Size(tmp);
    Py_XDECREF(tmp);
  /* Get the number of extra arguments */
  if (xa != NULL)
    ext = PyTuple_Size((PyObject *)xa);
  /* Calculate the size of call-backs argument list */
  siz = MIN(maxnofargs+ext,tot);
  *nofargs = MAX(0,siz-ext);
#ifdef DEBUGCFUNCS
  fprintf(stderr,"debug-capi:create_cb_arglist:maxnofargs(-nofoptargs),tot,opt,ext,siz,nofargs=%d(-%d),%d,%d,%d,%d,%d\n",maxnofargs,nofoptargs,tot,opt,ext,siz,*nofargs);
#endif
  if (siz<tot-opt) {
    fprintf(stderr,"create_cb_arglist: Failed to build argument list (siz) with enough arguments (tot-opt) required by user-supplied function (siz,tot,opt=%d,%d,%d).\n",siz,tot,opt);
    goto capi_fail;
  }
  /* Initialize argument list */
  *args = (PyTupleObject *)PyTuple_New(siz);
  for (i=0;i<*nofargs;i++) {
    Py_INCREF(Py_None);
    PyTuple_SET_ITEM((PyObject *)(*args),i,Py_None);
  }
  if (xa != NULL)
    for (i=(*nofargs);i<siz;i++) {
      tmp = PyTuple_GetItem((PyObject *)xa,i-(*nofargs));
      Py_INCREF(tmp);
      PyTuple_SET_ITEM(*args,i,tmp);
    }
  CFUNCSMESS("create_cb_arglist-end\n");
  return 1;
capi_fail:
  if ((PyErr_Occurred())==NULL)
    PyErr_SetString(slsqp_error,errmess);
  return 0;
}


/********************* See f2py2e/cfuncs.py: userincludes *********************/
/*need_userincludes*/

/********************* See f2py2e/capi_rules.py: usercode *********************/


/* See f2py2e/rules.py */
extern void F_FUNC(slsqp,SLSQP)(int*,int*,int*,int*,double*,double*,double*,double*,double*,double*,double*,double*,int*,int*,int*,string,int*,double*,int*,int*,int*,int*,int*,cb_slfunc_in_slsqp__user__routines_typedef,cb_slgrad_in_slsqp__user__routines_typedef,size_t);
extern void F_FUNC(openunit,OPENUNIT)(int*,string,string,string,int*,size_t,size_t,size_t);
extern void F_FUNC(pyflush,PYFLUSH)(int*);
extern void F_FUNC(closeunit,CLOSEUNIT)(int*);
/*eof externroutines*/

/******************** See f2py2e/capi_rules.py: usercode1 ********************/


/******************* See f2py2e/cb_rules.py: buildcallback *******************/

/********************* cb_slfunc_in_slsqp__user__routines *********************/
PyObject *cb_slfunc_in_slsqp__user__routines_capi = NULL;/*was Py_None*/
PyTupleObject *cb_slfunc_in_slsqp__user__routines_args_capi = NULL;
int cb_slfunc_in_slsqp__user__routines_nofargs = 0;
jmp_buf cb_slfunc_in_slsqp__user__routines_jmpbuf;
/*typedef void(*cb_slfunc_in_slsqp__user__routines_typedef)(int *,int *,int *,int *,double *,double *,double *);*/
static void cb_slfunc_in_slsqp__user__routines (int *m_cb_capi,int *meq_cb_capi,int *la_cb_capi,int *n_cb_capi,double *f_cb_capi,double *c,double *x) {
  PyTupleObject *capi_arglist = cb_slfunc_in_slsqp__user__routines_args_capi;
  PyObject *capi_return = NULL;
  PyObject *capi_tmp = NULL;
  int capi_j,capi_i = 0;
  int capi_longjmp_ok = 1;
/*decl*/
  int m=(*m_cb_capi);
  int meq=(*meq_cb_capi);
  int la=(*la_cb_capi);
  int n=(*n_cb_capi);
  double f=(*f_cb_capi);
  npy_intp c_Dims[1] = {-1};
  npy_intp x_Dims[1] = {-1};
#ifdef F2PY_REPORT_ATEXIT
f2py_cb_start_clock();
#endif
  CFUNCSMESS("cb:Call-back function cb_slfunc_in_slsqp__user__routines (maxnofargs=7(-0))\n");
  CFUNCSMESSPY("cb:cb_slfunc_in_slsqp__user__routines_capi=",cb_slfunc_in_slsqp__user__routines_capi);
  if (cb_slfunc_in_slsqp__user__routines_capi==NULL) {
    capi_longjmp_ok = 0;
    cb_slfunc_in_slsqp__user__routines_capi = PyObject_GetAttrString(slsqp_module,"slfunc");
  }
  if (cb_slfunc_in_slsqp__user__routines_capi==NULL) {
    PyErr_SetString(slsqp_error,"cb: Callback slfunc not defined (as an argument or module slsqp attribute).\n");
    goto capi_fail;
  }
  if (F2PyCapsule_Check(cb_slfunc_in_slsqp__user__routines_capi)) {
  cb_slfunc_in_slsqp__user__routines_typedef cb_slfunc_in_slsqp__user__routines_cptr;
  cb_slfunc_in_slsqp__user__routines_cptr = F2PyCapsule_AsVoidPtr(cb_slfunc_in_slsqp__user__routines_capi);
  (*cb_slfunc_in_slsqp__user__routines_cptr)(m_cb_capi,meq_cb_capi,la_cb_capi,n_cb_capi,f_cb_capi,c,x);
  return;
  }
  if (capi_arglist==NULL) {
    capi_longjmp_ok = 0;
    capi_tmp = PyObject_GetAttrString(slsqp_module,"slfunc_extra_args");
    if (capi_tmp) {
      capi_arglist = (PyTupleObject *)PySequence_Tuple(capi_tmp);
      if (capi_arglist==NULL) {
        PyErr_SetString(slsqp_error,"Failed to convert slsqp.slfunc_extra_args to tuple.\n");
        goto capi_fail;
      }
    } else {
      PyErr_Clear();
      capi_arglist = (PyTupleObject *)Py_BuildValue("()");
    }
  }
  if (capi_arglist == NULL) {
    PyErr_SetString(slsqp_error,"Callback slfunc argument list is not set.\n");
    goto capi_fail;
  }
/*setdims*/
  c_Dims[0]=la;
  x_Dims[0]=n;
/*pyobjfrom*/
  if (cb_slfunc_in_slsqp__user__routines_nofargs>capi_i)
    if (PyTuple_SetItem((PyObject *)capi_arglist,capi_i++,pyobj_from_int1(m)))
      goto capi_fail;
  if (cb_slfunc_in_slsqp__user__routines_nofargs>capi_i)
    if (PyTuple_SetItem((PyObject *)capi_arglist,capi_i++,pyobj_from_int1(meq)))
      goto capi_fail;
  if (cb_slfunc_in_slsqp__user__routines_nofargs>capi_i)
    if (PyTuple_SetItem((PyObject *)capi_arglist,capi_i++,pyobj_from_int1(la)))
      goto capi_fail;
  if (cb_slfunc_in_slsqp__user__routines_nofargs>capi_i)
    if (PyTuple_SetItem((PyObject *)capi_arglist,capi_i++,pyobj_from_int1(n)))
      goto capi_fail;
  if (cb_slfunc_in_slsqp__user__routines_nofargs>capi_i)
    if (PyTuple_SetItem((PyObject *)capi_arglist,capi_i++,pyobj_from_double1(f)))
      goto capi_fail;
  if (cb_slfunc_in_slsqp__user__routines_nofargs>capi_i) {
    PyArrayObject *tmp_arr = (PyArrayObject *)PyArray_New(&PyArray_Type,1,c_Dims,NPY_DOUBLE,NULL,(char*)c,0,NPY_FARRAY,NULL); /*XXX: Hmm, what will destroy this array??? */


    if (tmp_arr==NULL)
      goto capi_fail;
    if (PyTuple_SetItem((PyObject *)capi_arglist,capi_i++,(PyObject *)tmp_arr))
      goto capi_fail;
}
  if (cb_slfunc_in_slsqp__user__routines_nofargs>capi_i) {
    PyArrayObject *tmp_arr = (PyArrayObject *)PyArray_New(&PyArray_Type,1,x_Dims,NPY_DOUBLE,NULL,(char*)x,0,NPY_FARRAY,NULL); /*XXX: Hmm, what will destroy this array??? */


    if (tmp_arr==NULL)
      goto capi_fail;
    if (PyTuple_SetItem((PyObject *)capi_arglist,capi_i++,(PyObject *)tmp_arr))
      goto capi_fail;
}
  CFUNCSMESSPY("cb:capi_arglist=",capi_arglist);
  CFUNCSMESS("cb:Call-back calling Python function slfunc.\n");
#ifdef F2PY_REPORT_ATEXIT
f2py_cb_start_call_clock();
#endif
  capi_return = PyObject_CallObject(cb_slfunc_in_slsqp__user__routines_capi,(PyObject *)capi_arglist);
#ifdef F2PY_REPORT_ATEXIT
f2py_cb_stop_call_clock();
#endif
  CFUNCSMESSPY("cb:capi_return=",capi_return);
  if (capi_return == NULL) {
    fprintf(stderr,"capi_return is NULL\n");
    goto capi_fail;
  }
  if (capi_return == Py_None) {
    Py_DECREF(capi_return);
    capi_return = Py_BuildValue("()");
  }
  else if (!PyTuple_Check(capi_return)) {
    capi_return = Py_BuildValue("(N)",capi_return);
  }
  capi_j = PyTuple_Size(capi_return);
  capi_i = 0;
/*frompyobj*/
  if (capi_j>capi_i)
    GETSCALARFROMPYTUPLE(capi_return,capi_i++,f_cb_capi,double,"double_from_pyobj failed in converting argument f of call-back function cb_slfunc_in_slsqp__user__routines to C double\n");
  if (capi_j>capi_i) {
    PyArrayObject *rv_cb_arr = NULL;
    if ((capi_tmp = PyTuple_GetItem(capi_return,capi_i++))==NULL) goto capi_fail;
    rv_cb_arr =  array_from_pyobj(NPY_DOUBLE,c_Dims,1,F2PY_INTENT_IN
,capi_tmp);
    if (rv_cb_arr == NULL) {
      fprintf(stderr,"rv_cb_arr is NULL\n");
      goto capi_fail;
    }
    MEMCOPY(c,rv_cb_arr->data,PyArray_NBYTES(rv_cb_arr));
    if (capi_tmp != (PyObject *)rv_cb_arr) {
      Py_DECREF(rv_cb_arr);
    }
  }
  CFUNCSMESS("cb:cb_slfunc_in_slsqp__user__routines:successful\n");
  Py_DECREF(capi_return);
#ifdef F2PY_REPORT_ATEXIT
f2py_cb_stop_clock();
#endif
  goto capi_return_pt;
capi_fail:
  fprintf(stderr,"Call-back cb_slfunc_in_slsqp__user__routines failed.\n");
  Py_XDECREF(capi_return);
  if (capi_longjmp_ok)
    longjmp(cb_slfunc_in_slsqp__user__routines_jmpbuf,-1);
capi_return_pt:
  ;
return;
}
/***************** end of cb_slfunc_in_slsqp__user__routines *****************/


/********************* cb_slgrad_in_slsqp__user__routines *********************/
PyObject *cb_slgrad_in_slsqp__user__routines_capi = NULL;/*was Py_None*/
PyTupleObject *cb_slgrad_in_slsqp__user__routines_args_capi = NULL;
int cb_slgrad_in_slsqp__user__routines_nofargs = 0;
jmp_buf cb_slgrad_in_slsqp__user__routines_jmpbuf;
/*typedef void(*cb_slgrad_in_slsqp__user__routines_typedef)(int *,int *,int *,int *,double *,double *,double *,double *,double *);*/
static void cb_slgrad_in_slsqp__user__routines (int *m_cb_capi,int *meq_cb_capi,int *la_cb_capi,int *n_cb_capi,double *f_cb_capi,double *c,double *g,double *a,double *x) {
  PyTupleObject *capi_arglist = cb_slgrad_in_slsqp__user__routines_args_capi;
  PyObject *capi_return = NULL;
  PyObject *capi_tmp = NULL;
  int capi_j,capi_i = 0;
  int capi_longjmp_ok = 1;
/*decl*/
  int m=(*m_cb_capi);
  int meq=(*meq_cb_capi);
  int la=(*la_cb_capi);
  int n=(*n_cb_capi);
  double f=(*f_cb_capi);
  npy_intp a_Dims[2] = {-1, -1};
  npy_intp c_Dims[1] = {-1};
  npy_intp g_Dims[1] = {-1};
  npy_intp x_Dims[1] = {-1};
#ifdef F2PY_REPORT_ATEXIT
f2py_cb_start_clock();
#endif
  CFUNCSMESS("cb:Call-back function cb_slgrad_in_slsqp__user__routines (maxnofargs=9(-0))\n");
  CFUNCSMESSPY("cb:cb_slgrad_in_slsqp__user__routines_capi=",cb_slgrad_in_slsqp__user__routines_capi);
  if (cb_slgrad_in_slsqp__user__routines_capi==NULL) {
    capi_longjmp_ok = 0;
    cb_slgrad_in_slsqp__user__routines_capi = PyObject_GetAttrString(slsqp_module,"slgrad");
  }
  if (cb_slgrad_in_slsqp__user__routines_capi==NULL) {
    PyErr_SetString(slsqp_error,"cb: Callback slgrad not defined (as an argument or module slsqp attribute).\n");
    goto capi_fail;
  }
  if (F2PyCapsule_Check(cb_slgrad_in_slsqp__user__routines_capi)) {
  cb_slgrad_in_slsqp__user__routines_typedef cb_slgrad_in_slsqp__user__routines_cptr;
  cb_slgrad_in_slsqp__user__routines_cptr = F2PyCapsule_AsVoidPtr(cb_slgrad_in_slsqp__user__routines_capi);
  (*cb_slgrad_in_slsqp__user__routines_cptr)(m_cb_capi,meq_cb_capi,la_cb_capi,n_cb_capi,f_cb_capi,c,g,a,x);
  return;
  }
  if (capi_arglist==NULL) {
    capi_longjmp_ok = 0;
    capi_tmp = PyObject_GetAttrString(slsqp_module,"slgrad_extra_args");
    if (capi_tmp) {
      capi_arglist = (PyTupleObject *)PySequence_Tuple(capi_tmp);
      if (capi_arglist==NULL) {
        PyErr_SetString(slsqp_error,"Failed to convert slsqp.slgrad_extra_args to tuple.\n");
        goto capi_fail;
      }
    } else {
      PyErr_Clear();
      capi_arglist = (PyTupleObject *)Py_BuildValue("()");
    }
  }
  if (capi_arglist == NULL) {
    PyErr_SetString(slsqp_error,"Callback slgrad argument list is not set.\n");
    goto capi_fail;
  }
/*setdims*/
  a_Dims[0]=la,a_Dims[1]=n + 1;
  c_Dims[0]=la;
  g_Dims[0]=n + 1;
  x_Dims[0]=n;
/*pyobjfrom*/
  if (cb_slgrad_in_slsqp__user__routines_nofargs>capi_i)
    if (PyTuple_SetItem((PyObject *)capi_arglist,capi_i++,pyobj_from_int1(m)))
      goto capi_fail;
  if (cb_slgrad_in_slsqp__user__routines_nofargs>capi_i)
    if (PyTuple_SetItem((PyObject *)capi_arglist,capi_i++,pyobj_from_int1(meq)))
      goto capi_fail;
  if (cb_slgrad_in_slsqp__user__routines_nofargs>capi_i)
    if (PyTuple_SetItem((PyObject *)capi_arglist,capi_i++,pyobj_from_int1(la)))
      goto capi_fail;
  if (cb_slgrad_in_slsqp__user__routines_nofargs>capi_i)
    if (PyTuple_SetItem((PyObject *)capi_arglist,capi_i++,pyobj_from_int1(n)))
      goto capi_fail;
  if (cb_slgrad_in_slsqp__user__routines_nofargs>capi_i)
    if (PyTuple_SetItem((PyObject *)capi_arglist,capi_i++,pyobj_from_double1(f)))
      goto capi_fail;
  if (cb_slgrad_in_slsqp__user__routines_nofargs>capi_i) {
    PyArrayObject *tmp_arr = (PyArrayObject *)PyArray_New(&PyArray_Type,1,c_Dims,NPY_DOUBLE,NULL,(char*)c,0,NPY_FARRAY,NULL); /*XXX: Hmm, what will destroy this array??? */


    if (tmp_arr==NULL)
      goto capi_fail;
    if (PyTuple_SetItem((PyObject *)capi_arglist,capi_i++,(PyObject *)tmp_arr))
      goto capi_fail;
}
  if (cb_slgrad_in_slsqp__user__routines_nofargs>capi_i) {
    PyArrayObject *tmp_arr = (PyArrayObject *)PyArray_New(&PyArray_Type,1,g_Dims,NPY_DOUBLE,NULL,(char*)g,0,NPY_FARRAY,NULL); /*XXX: Hmm, what will destroy this array??? */


    if (tmp_arr==NULL)
      goto capi_fail;
    if (PyTuple_SetItem((PyObject *)capi_arglist,capi_i++,(PyObject *)tmp_arr))
      goto capi_fail;
}
  if (cb_slgrad_in_slsqp__user__routines_nofargs>capi_i) {
    PyArrayObject *tmp_arr = (PyArrayObject *)PyArray_New(&PyArray_Type,2,a_Dims,NPY_DOUBLE,NULL,(char*)a,0,NPY_FARRAY,NULL); /*XXX: Hmm, what will destroy this array??? */


    if (tmp_arr==NULL)
      goto capi_fail;
    if (PyTuple_SetItem((PyObject *)capi_arglist,capi_i++,(PyObject *)tmp_arr))
      goto capi_fail;
}
  if (cb_slgrad_in_slsqp__user__routines_nofargs>capi_i) {
    PyArrayObject *tmp_arr = (PyArrayObject *)PyArray_New(&PyArray_Type,1,x_Dims,NPY_DOUBLE,NULL,(char*)x,0,NPY_FARRAY,NULL); /*XXX: Hmm, what will destroy this array??? */


    if (tmp_arr==NULL)
      goto capi_fail;
    if (PyTuple_SetItem((PyObject *)capi_arglist,capi_i++,(PyObject *)tmp_arr))
      goto capi_fail;
}
  CFUNCSMESSPY("cb:capi_arglist=",capi_arglist);
  CFUNCSMESS("cb:Call-back calling Python function slgrad.\n");
#ifdef F2PY_REPORT_ATEXIT
f2py_cb_start_call_clock();
#endif
  capi_return = PyObject_CallObject(cb_slgrad_in_slsqp__user__routines_capi,(PyObject *)capi_arglist);
#ifdef F2PY_REPORT_ATEXIT
f2py_cb_stop_call_clock();
#endif
  CFUNCSMESSPY("cb:capi_return=",capi_return);
  if (capi_return == NULL) {
    fprintf(stderr,"capi_return is NULL\n");
    goto capi_fail;
  }
  if (capi_return == Py_None) {
    Py_DECREF(capi_return);
    capi_return = Py_BuildValue("()");
  }
  else if (!PyTuple_Check(capi_return)) {
    capi_return = Py_BuildValue("(N)",capi_return);
  }
  capi_j = PyTuple_Size(capi_return);
  capi_i = 0;
/*frompyobj*/
  if (capi_j>capi_i) {
    PyArrayObject *rv_cb_arr = NULL;
    if ((capi_tmp = PyTuple_GetItem(capi_return,capi_i++))==NULL) goto capi_fail;
    rv_cb_arr =  array_from_pyobj(NPY_DOUBLE,g_Dims,1,F2PY_INTENT_IN
,capi_tmp);
    if (rv_cb_arr == NULL) {
      fprintf(stderr,"rv_cb_arr is NULL\n");
      goto capi_fail;
    }
    MEMCOPY(g,rv_cb_arr->data,PyArray_NBYTES(rv_cb_arr));
    if (capi_tmp != (PyObject *)rv_cb_arr) {
      Py_DECREF(rv_cb_arr);
    }
  }
  if (capi_j>capi_i) {
    PyArrayObject *rv_cb_arr = NULL;
    if ((capi_tmp = PyTuple_GetItem(capi_return,capi_i++))==NULL) goto capi_fail;
    rv_cb_arr =  array_from_pyobj(NPY_DOUBLE,a_Dims,2,F2PY_INTENT_IN
,capi_tmp);
    if (rv_cb_arr == NULL) {
      fprintf(stderr,"rv_cb_arr is NULL\n");
      goto capi_fail;
    }
    MEMCOPY(a,rv_cb_arr->data,PyArray_NBYTES(rv_cb_arr));
    if (capi_tmp != (PyObject *)rv_cb_arr) {
      Py_DECREF(rv_cb_arr);
    }
  }
  CFUNCSMESS("cb:cb_slgrad_in_slsqp__user__routines:successful\n");
  Py_DECREF(capi_return);
#ifdef F2PY_REPORT_ATEXIT
f2py_cb_stop_clock();
#endif
  goto capi_return_pt;
capi_fail:
  fprintf(stderr,"Call-back cb_slgrad_in_slsqp__user__routines failed.\n");
  Py_XDECREF(capi_return);
  if (capi_longjmp_ok)
    longjmp(cb_slgrad_in_slsqp__user__routines_jmpbuf,-1);
capi_return_pt:
  ;
return;
}
/***************** end of cb_slgrad_in_slsqp__user__routines *****************/


/*********************** See f2py2e/rules.py: buildapi ***********************/

/*********************************** slsqp ***********************************/
static char doc_f2py_rout_slsqp_slsqp[] = "\
Function signature:\n\
  a = slsqp(m,meq,la,n,x,xl,xu,f,c,g,a,acc,iter,iprint,iout,ifile,mode,w,l_w,jw,l_jw,nfunc,ngrad,slfunc,slgrad,[slfunc_extra_args,slgrad_extra_args])\n\
Required arguments:\n"
"  m : input int\n"
"  meq : input int\n"
"  la : input int\n"
"  n : input int\n"
"  x : in/output rank-1 array('d') with bounds (n)\n"
"  xl : input rank-1 array('d') with bounds (n)\n"
"  xu : input rank-1 array('d') with bounds (n)\n"
"  f : in/output rank-0 array(float,'d')\n"
"  c : in/output rank-1 array('d') with bounds (la)\n"
"  g : in/output rank-1 array('d') with bounds (n + 1)\n"
"  a : input rank-2 array('d') with bounds (la,n + 1)\n"
"  acc : input float\n"
"  iter : in/output rank-0 array(int,'i')\n"
"  iprint : input int\n"
"  iout : input int\n"
"  ifile : input string(len=-1)\n"
"  mode : in/output rank-0 array(int,'i')\n"
"  w : in/output rank-1 array('d') with bounds (l_w)\n"
"  l_w : input int\n"
"  jw : in/output rank-1 array('i') with bounds (l_jw)\n"
"  l_jw : input int\n"
"  nfunc : in/output rank-0 array(int,'i')\n"
"  ngrad : in/output rank-0 array(int,'i')\n"
"  slfunc : call-back function\n"
"  slgrad : call-back function\n"
"Optional arguments:\n"
"  slfunc_extra_args := () input tuple\n"
"  slgrad_extra_args := () input tuple\n"
"Return objects:\n"
"  a : rank-2 array('d') with bounds (la,n + 1)\n"
"Call-back functions:\n"
"  def slfunc(m,meq,la,n,f,c,x): return f,c\n\
  Required arguments:\n"
"    m : input int\n"
"    meq : input int\n"
"    la : input int\n"
"    n : input int\n"
"    f : input float\n"
"    c : input rank-1 array('d') with bounds (la)\n"
"    x : input rank-1 array('d') with bounds (n)\n"
"  Return objects:\n"
"    f : float\n"
"    c : rank-1 array('d') with bounds (la)\n"
"  def slgrad(m,meq,la,n,f,c,g,a,x): return g,a\n\
  Required arguments:\n"
"    m : input int\n"
"    meq : input int\n"
"    la : input int\n"
"    n : input int\n"
"    f : input float\n"
"    c : input rank-1 array('d') with bounds (la)\n"
"    g : input rank-1 array('d') with bounds (n + 1)\n"
"    a : input rank-2 array('d') with bounds (la,n + 1)\n"
"    x : input rank-1 array('d') with bounds (n)\n"
"  Return objects:\n"
"    g : rank-1 array('d') with bounds (n + 1)\n"
"    a : rank-2 array('d') with bounds (la,n + 1)";
/* extern void F_FUNC(slsqp,SLSQP)(int*,int*,int*,int*,double*,double*,double*,double*,double*,double*,double*,double*,int*,int*,int*,string,int*,double*,int*,int*,int*,int*,int*,cb_slfunc_in_slsqp__user__routines_typedef,cb_slgrad_in_slsqp__user__routines_typedef,size_t); */
static PyObject *f2py_rout_slsqp_slsqp(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*,int*,int*,int*,double*,double*,double*,double*,double*,double*,double*,double*,int*,int*,int*,string,int*,double*,int*,int*,int*,int*,int*,cb_slfunc_in_slsqp__user__routines_typedef,cb_slgrad_in_slsqp__user__routines_typedef,size_t)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  int m = 0;
  PyObject *m_capi = Py_None;
  int meq = 0;
  PyObject *meq_capi = Py_None;
  int la = 0;
  PyObject *la_capi = Py_None;
  int n = 0;
  PyObject *n_capi = Py_None;
  double *x = NULL;
  npy_intp x_Dims[1] = {-1};
  const int x_Rank = 1;
  PyArrayObject *capi_x_tmp = NULL;
  int capi_x_intent = 0;
  PyObject *x_capi = Py_None;
  double *xl = NULL;
  npy_intp xl_Dims[1] = {-1};
  const int xl_Rank = 1;
  PyArrayObject *capi_xl_tmp = NULL;
  int capi_xl_intent = 0;
  PyObject *xl_capi = Py_None;
  double *xu = NULL;
  npy_intp xu_Dims[1] = {-1};
  const int xu_Rank = 1;
  PyArrayObject *capi_xu_tmp = NULL;
  int capi_xu_intent = 0;
  PyObject *xu_capi = Py_None;
  double f = 0;
  PyObject *f_capi = Py_None;
  double *c = NULL;
  npy_intp c_Dims[1] = {-1};
  const int c_Rank = 1;
  PyArrayObject *capi_c_tmp = NULL;
  int capi_c_intent = 0;
  PyObject *c_capi = Py_None;
  double *g = NULL;
  npy_intp g_Dims[1] = {-1};
  const int g_Rank = 1;
  PyArrayObject *capi_g_tmp = NULL;
  int capi_g_intent = 0;
  PyObject *g_capi = Py_None;
  double *a = NULL;
  npy_intp a_Dims[2] = {-1, -1};
  const int a_Rank = 2;
  PyArrayObject *capi_a_tmp = NULL;
  int capi_a_intent = 0;
  PyObject *a_capi = Py_None;
  double acc = 0;
  PyObject *acc_capi = Py_None;
  int iter = 0;
  PyObject *iter_capi = Py_None;
  int iprint = 0;
  PyObject *iprint_capi = Py_None;
  int iout = 0;
  PyObject *iout_capi = Py_None;
  string ifile = NULL;
  int slen(ifile);
  PyObject *ifile_capi = Py_None;
  int mode = 0;
  PyObject *mode_capi = Py_None;
  double *w = NULL;
  npy_intp w_Dims[1] = {-1};
  const int w_Rank = 1;
  PyArrayObject *capi_w_tmp = NULL;
  int capi_w_intent = 0;
  PyObject *w_capi = Py_None;
  int l_w = 0;
  PyObject *l_w_capi = Py_None;
  int *jw = NULL;
  npy_intp jw_Dims[1] = {-1};
  const int jw_Rank = 1;
  PyArrayObject *capi_jw_tmp = NULL;
  int capi_jw_intent = 0;
  PyObject *jw_capi = Py_None;
  int l_jw = 0;
  PyObject *l_jw_capi = Py_None;
  int nfunc = 0;
  PyObject *nfunc_capi = Py_None;
  int ngrad = 0;
  PyObject *ngrad_capi = Py_None;
  PyObject *slfunc_capi = Py_None;
  PyTupleObject *slfunc_xa_capi = NULL;
  PyTupleObject *slfunc_args_capi = NULL;
  int slfunc_nofargs_capi = 0;
  cb_slfunc_in_slsqp__user__routines_typedef slfunc_cptr;
  PyObject *slgrad_capi = Py_None;
  PyTupleObject *slgrad_xa_capi = NULL;
  PyTupleObject *slgrad_args_capi = NULL;
  int slgrad_nofargs_capi = 0;
  cb_slgrad_in_slsqp__user__routines_typedef slgrad_cptr;
  static char *capi_kwlist[] = {"m","meq","la","n","x","xl","xu","f","c","g","a","acc","iter","iprint","iout","ifile","mode","w","l_w","jw","l_jw","nfunc","ngrad","slfunc","slgrad","slfunc_extra_args","slgrad_extra_args",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOOOOOOOOOOOOOOOOOOOOOOOO|O!O!:slsqp.slsqp",\
    capi_kwlist,&m_capi,&meq_capi,&la_capi,&n_capi,&x_capi,&xl_capi,&xu_capi,&f_capi,&c_capi,&g_capi,&a_capi,&acc_capi,&iter_capi,&iprint_capi,&iout_capi,&ifile_capi,&mode_capi,&w_capi,&l_w_capi,&jw_capi,&l_jw_capi,&nfunc_capi,&ngrad_capi,&slfunc_capi,&slgrad_capi,&PyTuple_Type,&slfunc_xa_capi,&PyTuple_Type,&slgrad_xa_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable l_jw */
    f2py_success = int_from_pyobj(&l_jw,l_jw_capi,"slsqp.slsqp() 21st argument (l_jw) can't be converted to int");
  if (f2py_success) {
  /* Processing variable iout */
    f2py_success = int_from_pyobj(&iout,iout_capi,"slsqp.slsqp() 15th argument (iout) can't be converted to int");
  if (f2py_success) {
  /* Processing variable nfunc */
    f2py_success = int_from_pyobj(&nfunc,nfunc_capi,"slsqp.slsqp() 22nd argument (nfunc) can't be converted to int");
  if (f2py_success) {
  /* Processing variable meq */
    f2py_success = int_from_pyobj(&meq,meq_capi,"slsqp.slsqp() 2nd argument (meq) can't be converted to int");
  if (f2py_success) {
  /* Processing variable ngrad */
    f2py_success = int_from_pyobj(&ngrad,ngrad_capi,"slsqp.slsqp() 23rd argument (ngrad) can't be converted to int");
  if (f2py_success) {
  /* Processing variable acc */
    f2py_success = double_from_pyobj(&acc,acc_capi,"slsqp.slsqp() 12nd argument (acc) can't be converted to double");
  if (f2py_success) {
  /* Processing variable ifile */
  slen(ifile) = -1;
  f2py_success = string_from_pyobj(&ifile,&slen(ifile),"",ifile_capi,"string_from_pyobj failed in converting 16th argument `ifile' of slsqp.slsqp to C string");
  if (f2py_success) {
  /* Processing variable l_w */
    f2py_success = int_from_pyobj(&l_w,l_w_capi,"slsqp.slsqp() 19th argument (l_w) can't be converted to int");
  if (f2py_success) {
  /* Processing variable la */
    f2py_success = int_from_pyobj(&la,la_capi,"slsqp.slsqp() 3rd argument (la) can't be converted to int");
  if (f2py_success) {
  /* Processing variable iprint */
    f2py_success = int_from_pyobj(&iprint,iprint_capi,"slsqp.slsqp() 14th argument (iprint) can't be converted to int");
  if (f2py_success) {
  /* Processing variable f */
    f2py_success = double_from_pyobj(&f,f_capi,"slsqp.slsqp() 8th argument (f) can't be converted to double");
  if (f2py_success) {
  /* Processing variable m */
    f2py_success = int_from_pyobj(&m,m_capi,"slsqp.slsqp() 1st argument (m) can't be converted to int");
  if (f2py_success) {
  /* Processing variable iter */
    f2py_success = int_from_pyobj(&iter,iter_capi,"slsqp.slsqp() 13rd argument (iter) can't be converted to int");
  if (f2py_success) {
  /* Processing variable slgrad */
if(F2PyCapsule_Check(slgrad_capi)) {
  slgrad_cptr = F2PyCapsule_AsVoidPtr(slgrad_capi);
} else {
  slgrad_cptr = cb_slgrad_in_slsqp__user__routines;
}

  slgrad_nofargs_capi = cb_slgrad_in_slsqp__user__routines_nofargs;
  if (create_cb_arglist(slgrad_capi,slgrad_xa_capi,9,0,&cb_slgrad_in_slsqp__user__routines_nofargs,&slgrad_args_capi,"failed in processing argument list for call-back slgrad.")) {
    jmp_buf slgrad_jmpbuf;
    CFUNCSMESS("Saving jmpbuf for `slgrad`.\n");
    SWAP(slgrad_capi,cb_slgrad_in_slsqp__user__routines_capi,PyObject);
    SWAP(slgrad_args_capi,cb_slgrad_in_slsqp__user__routines_args_capi,PyTupleObject);
    memcpy(&slgrad_jmpbuf,&cb_slgrad_in_slsqp__user__routines_jmpbuf,sizeof(jmp_buf));
  /* Processing variable n */
    f2py_success = int_from_pyobj(&n,n_capi,"slsqp.slsqp() 4th argument (n) can't be converted to int");
  if (f2py_success) {
  /* Processing variable mode */
    f2py_success = int_from_pyobj(&mode,mode_capi,"slsqp.slsqp() 17th argument (mode) can't be converted to int");
  if (f2py_success) {
  /* Processing variable slfunc */
if(F2PyCapsule_Check(slfunc_capi)) {
  slfunc_cptr = F2PyCapsule_AsVoidPtr(slfunc_capi);
} else {
  slfunc_cptr = cb_slfunc_in_slsqp__user__routines;
}

  slfunc_nofargs_capi = cb_slfunc_in_slsqp__user__routines_nofargs;
  if (create_cb_arglist(slfunc_capi,slfunc_xa_capi,7,0,&cb_slfunc_in_slsqp__user__routines_nofargs,&slfunc_args_capi,"failed in processing argument list for call-back slfunc.")) {
    jmp_buf slfunc_jmpbuf;
    CFUNCSMESS("Saving jmpbuf for `slfunc`.\n");
    SWAP(slfunc_capi,cb_slfunc_in_slsqp__user__routines_capi,PyObject);
    SWAP(slfunc_args_capi,cb_slfunc_in_slsqp__user__routines_args_capi,PyTupleObject);
    memcpy(&slfunc_jmpbuf,&cb_slfunc_in_slsqp__user__routines_jmpbuf,sizeof(jmp_buf));
  /* Processing variable a */
  a_Dims[0]=la,a_Dims[1]=n + 1;
  capi_a_intent |= F2PY_INTENT_OUT|F2PY_INTENT_IN;
  capi_a_tmp = array_from_pyobj(NPY_DOUBLE,a_Dims,a_Rank,capi_a_intent,a_capi);
  if (capi_a_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(slsqp_error,"failed in converting 11st argument `a' of slsqp.slsqp to C/Fortran array" );
  } else {
    a = (double *)(capi_a_tmp->data);

  /* Processing variable xl */
  xl_Dims[0]=n;
  capi_xl_intent |= F2PY_INTENT_IN;
  capi_xl_tmp = array_from_pyobj(NPY_DOUBLE,xl_Dims,xl_Rank,capi_xl_intent,xl_capi);
  if (capi_xl_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(slsqp_error,"failed in converting 6th argument `xl' of slsqp.slsqp to C/Fortran array" );
  } else {
    xl = (double *)(capi_xl_tmp->data);

  /* Processing variable jw */
  jw_Dims[0]=l_jw;
  capi_jw_intent |= F2PY_INTENT_INOUT;
  capi_jw_tmp = array_from_pyobj(NPY_INT,jw_Dims,jw_Rank,capi_jw_intent,jw_capi);
  if (capi_jw_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(slsqp_error,"failed in converting 20th argument `jw' of slsqp.slsqp to C/Fortran array" );
  } else {
    jw = (int *)(capi_jw_tmp->data);

  /* Processing variable c */
  c_Dims[0]=la;
  capi_c_intent |= F2PY_INTENT_INOUT;
  capi_c_tmp = array_from_pyobj(NPY_DOUBLE,c_Dims,c_Rank,capi_c_intent,c_capi);
  if (capi_c_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(slsqp_error,"failed in converting 9th argument `c' of slsqp.slsqp to C/Fortran array" );
  } else {
    c = (double *)(capi_c_tmp->data);

  /* Processing variable x */
  x_Dims[0]=n;
  capi_x_intent |= F2PY_INTENT_INOUT;
  capi_x_tmp = array_from_pyobj(NPY_DOUBLE,x_Dims,x_Rank,capi_x_intent,x_capi);
  if (capi_x_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(slsqp_error,"failed in converting 5th argument `x' of slsqp.slsqp to C/Fortran array" );
  } else {
    x = (double *)(capi_x_tmp->data);

  /* Processing variable xu */
  xu_Dims[0]=n;
  capi_xu_intent |= F2PY_INTENT_IN;
  capi_xu_tmp = array_from_pyobj(NPY_DOUBLE,xu_Dims,xu_Rank,capi_xu_intent,xu_capi);
  if (capi_xu_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(slsqp_error,"failed in converting 7th argument `xu' of slsqp.slsqp to C/Fortran array" );
  } else {
    xu = (double *)(capi_xu_tmp->data);

  /* Processing variable g */
  g_Dims[0]=n + 1;
  capi_g_intent |= F2PY_INTENT_INOUT;
  capi_g_tmp = array_from_pyobj(NPY_DOUBLE,g_Dims,g_Rank,capi_g_intent,g_capi);
  if (capi_g_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(slsqp_error,"failed in converting 10th argument `g' of slsqp.slsqp to C/Fortran array" );
  } else {
    g = (double *)(capi_g_tmp->data);

  /* Processing variable w */
  w_Dims[0]=l_w;
  capi_w_intent |= F2PY_INTENT_INOUT;
  capi_w_tmp = array_from_pyobj(NPY_DOUBLE,w_Dims,w_Rank,capi_w_intent,w_capi);
  if (capi_w_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(slsqp_error,"failed in converting 18th argument `w' of slsqp.slsqp to C/Fortran array" );
  } else {
    w = (double *)(capi_w_tmp->data);

/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
    if ((setjmp(cb_slfunc_in_slsqp__user__routines_jmpbuf)) || (setjmp(cb_slgrad_in_slsqp__user__routines_jmpbuf))) {
      f2py_success = 0;
    } else {
        (*f2py_func)(&m,&meq,&la,&n,x,xl,xu,&f,c,g,a,&acc,&iter,&iprint,&iout,ifile,&mode,w,&l_w,jw,&l_jw,&nfunc,&ngrad,slfunc_cptr,slgrad_cptr,slen(ifile));
    }
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
  f2py_success = try_pyarr_from_double(f_capi,&f);
  if (f2py_success) {
  f2py_success = try_pyarr_from_int(iter_capi,&iter);
  if (f2py_success) {
  f2py_success = try_pyarr_from_int(mode_capi,&mode);
  if (f2py_success) {
  f2py_success = try_pyarr_from_int(nfunc_capi,&nfunc);
  if (f2py_success) {
  f2py_success = try_pyarr_from_int(ngrad_capi,&ngrad);
  if (f2py_success) {
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("N",capi_a_tmp);
/*closepyobjfrom*/
  } /*if (f2py_success) of ngrad pyobjfrom*/
  } /*if (f2py_success) of nfunc pyobjfrom*/
  } /*if (f2py_success) of mode pyobjfrom*/
  } /*if (f2py_success) of iter pyobjfrom*/
  } /*if (f2py_success) of f pyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  if((PyObject *)capi_w_tmp!=w_capi) {
    Py_XDECREF(capi_w_tmp); }
  }  /*if (capi_w_tmp == NULL) ... else of w*/
  /* End of cleaning variable w */
  if((PyObject *)capi_g_tmp!=g_capi) {
    Py_XDECREF(capi_g_tmp); }
  }  /*if (capi_g_tmp == NULL) ... else of g*/
  /* End of cleaning variable g */
  if((PyObject *)capi_xu_tmp!=xu_capi) {
    Py_XDECREF(capi_xu_tmp); }
  }  /*if (capi_xu_tmp == NULL) ... else of xu*/
  /* End of cleaning variable xu */
  if((PyObject *)capi_x_tmp!=x_capi) {
    Py_XDECREF(capi_x_tmp); }
  }  /*if (capi_x_tmp == NULL) ... else of x*/
  /* End of cleaning variable x */
  if((PyObject *)capi_c_tmp!=c_capi) {
    Py_XDECREF(capi_c_tmp); }
  }  /*if (capi_c_tmp == NULL) ... else of c*/
  /* End of cleaning variable c */
  if((PyObject *)capi_jw_tmp!=jw_capi) {
    Py_XDECREF(capi_jw_tmp); }
  }  /*if (capi_jw_tmp == NULL) ... else of jw*/
  /* End of cleaning variable jw */
  if((PyObject *)capi_xl_tmp!=xl_capi) {
    Py_XDECREF(capi_xl_tmp); }
  }  /*if (capi_xl_tmp == NULL) ... else of xl*/
  /* End of cleaning variable xl */
  }  /*if (capi_a_tmp == NULL) ... else of a*/
  /* End of cleaning variable a */
    CFUNCSMESS("Restoring jmpbuf for `slfunc`.\n");
    cb_slfunc_in_slsqp__user__routines_capi = slfunc_capi;
    Py_DECREF(cb_slfunc_in_slsqp__user__routines_args_capi);
    cb_slfunc_in_slsqp__user__routines_args_capi = slfunc_args_capi;
    cb_slfunc_in_slsqp__user__routines_nofargs = slfunc_nofargs_capi;
    memcpy(&cb_slfunc_in_slsqp__user__routines_jmpbuf,&slfunc_jmpbuf,sizeof(jmp_buf));
  }
  /* End of cleaning variable slfunc */
  } /*if (f2py_success) of mode*/
  /* End of cleaning variable mode */
  } /*if (f2py_success) of n*/
  /* End of cleaning variable n */
    CFUNCSMESS("Restoring jmpbuf for `slgrad`.\n");
    cb_slgrad_in_slsqp__user__routines_capi = slgrad_capi;
    Py_DECREF(cb_slgrad_in_slsqp__user__routines_args_capi);
    cb_slgrad_in_slsqp__user__routines_args_capi = slgrad_args_capi;
    cb_slgrad_in_slsqp__user__routines_nofargs = slgrad_nofargs_capi;
    memcpy(&cb_slgrad_in_slsqp__user__routines_jmpbuf,&slgrad_jmpbuf,sizeof(jmp_buf));
  }
  /* End of cleaning variable slgrad */
  } /*if (f2py_success) of iter*/
  /* End of cleaning variable iter */
  } /*if (f2py_success) of m*/
  /* End of cleaning variable m */
  } /*if (f2py_success) of f*/
  /* End of cleaning variable f */
  } /*if (f2py_success) of iprint*/
  /* End of cleaning variable iprint */
  } /*if (f2py_success) of la*/
  /* End of cleaning variable la */
  } /*if (f2py_success) of l_w*/
  /* End of cleaning variable l_w */
    STRINGFREE(ifile);
  }  /*if (f2py_success) of ifile*/
  /* End of cleaning variable ifile */
  } /*if (f2py_success) of acc*/
  /* End of cleaning variable acc */
  } /*if (f2py_success) of ngrad*/
  /* End of cleaning variable ngrad */
  } /*if (f2py_success) of meq*/
  /* End of cleaning variable meq */
  } /*if (f2py_success) of nfunc*/
  /* End of cleaning variable nfunc */
  } /*if (f2py_success) of iout*/
  /* End of cleaning variable iout */
  } /*if (f2py_success) of l_jw*/
  /* End of cleaning variable l_jw */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/******************************** end of slsqp ********************************/

/********************************** openunit **********************************/
static char doc_f2py_rout_slsqp_openunit[] = "\
Function signature:\n\
  ierror = openunit(unitnum,filename,filestatus,fileaction)\n\
Required arguments:\n"
"  unitnum : input int\n"
"  filename : input string(len=-1)\n"
"  filestatus : input string(len=-1)\n"
"  fileaction : input string(len=-1)\n"
"Return objects:\n"
"  ierror : int";
/* extern void F_FUNC(openunit,OPENUNIT)(int*,string,string,string,int*,size_t,size_t,size_t); */
static PyObject *f2py_rout_slsqp_openunit(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*,string,string,string,int*,size_t,size_t,size_t)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  int unitnum = 0;
  PyObject *unitnum_capi = Py_None;
  string filename = NULL;
  int slen(filename);
  PyObject *filename_capi = Py_None;
  string filestatus = NULL;
  int slen(filestatus);
  PyObject *filestatus_capi = Py_None;
  string fileaction = NULL;
  int slen(fileaction);
  PyObject *fileaction_capi = Py_None;
  int ierror = 0;
  static char *capi_kwlist[] = {"unitnum","filename","filestatus","fileaction",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOOO:slsqp.openunit",\
    capi_kwlist,&unitnum_capi,&filename_capi,&filestatus_capi,&fileaction_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable filestatus */
  slen(filestatus) = -1;
  f2py_success = string_from_pyobj(&filestatus,&slen(filestatus),"",filestatus_capi,"string_from_pyobj failed in converting 3rd argument `filestatus' of slsqp.openunit to C string");
  if (f2py_success) {
  /* Processing variable filename */
  slen(filename) = -1;
  f2py_success = string_from_pyobj(&filename,&slen(filename),"",filename_capi,"string_from_pyobj failed in converting 2nd argument `filename' of slsqp.openunit to C string");
  if (f2py_success) {
  /* Processing variable unitnum */
    f2py_success = int_from_pyobj(&unitnum,unitnum_capi,"slsqp.openunit() 1st argument (unitnum) can't be converted to int");
  if (f2py_success) {
  /* Processing variable fileaction */
  slen(fileaction) = -1;
  f2py_success = string_from_pyobj(&fileaction,&slen(fileaction),"",fileaction_capi,"string_from_pyobj failed in converting 4th argument `fileaction' of slsqp.openunit to C string");
  if (f2py_success) {
  /* Processing variable ierror */
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(&unitnum,filename,filestatus,fileaction,&ierror,slen(filename),slen(filestatus),slen(fileaction));
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("i",ierror);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  /* End of cleaning variable ierror */
    STRINGFREE(fileaction);
  }  /*if (f2py_success) of fileaction*/
  /* End of cleaning variable fileaction */
  } /*if (f2py_success) of unitnum*/
  /* End of cleaning variable unitnum */
    STRINGFREE(filename);
  }  /*if (f2py_success) of filename*/
  /* End of cleaning variable filename */
    STRINGFREE(filestatus);
  }  /*if (f2py_success) of filestatus*/
  /* End of cleaning variable filestatus */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/****************************** end of openunit ******************************/

/********************************** pyflush **********************************/
static char doc_f2py_rout_slsqp_pyflush[] = "\
Function signature:\n\
  pyflush(unitnum)\n\
Required arguments:\n"
"  unitnum : input int";
/* extern void F_FUNC(pyflush,PYFLUSH)(int*); */
static PyObject *f2py_rout_slsqp_pyflush(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  int unitnum = 0;
  PyObject *unitnum_capi = Py_None;
  static char *capi_kwlist[] = {"unitnum",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "O:slsqp.pyflush",\
    capi_kwlist,&unitnum_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable unitnum */
    f2py_success = int_from_pyobj(&unitnum,unitnum_capi,"slsqp.pyflush() 1st argument (unitnum) can't be converted to int");
  if (f2py_success) {
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(&unitnum);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("");
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  } /*if (f2py_success) of unitnum*/
  /* End of cleaning variable unitnum */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/******************************* end of pyflush *******************************/

/********************************* closeunit *********************************/
static char doc_f2py_rout_slsqp_closeunit[] = "\
Function signature:\n\
  closeunit(unitnum)\n\
Required arguments:\n"
"  unitnum : input int";
/* extern void F_FUNC(closeunit,CLOSEUNIT)(int*); */
static PyObject *f2py_rout_slsqp_closeunit(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  int unitnum = 0;
  PyObject *unitnum_capi = Py_None;
  static char *capi_kwlist[] = {"unitnum",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "O:slsqp.closeunit",\
    capi_kwlist,&unitnum_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable unitnum */
    f2py_success = int_from_pyobj(&unitnum,unitnum_capi,"slsqp.closeunit() 1st argument (unitnum) can't be converted to int");
  if (f2py_success) {
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(&unitnum);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("");
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  } /*if (f2py_success) of unitnum*/
  /* End of cleaning variable unitnum */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/****************************** end of closeunit ******************************/
/*eof body*/

/******************* See f2py2e/f90mod_rules.py: buildhooks *******************/
/*need_f90modhooks*/

/************** See f2py2e/rules.py: module_rules['modulebody'] **************/

/******************* See f2py2e/common_rules.py: buildhooks *******************/

/*need_commonhooks*/

/**************************** See f2py2e/rules.py ****************************/

static FortranDataDef f2py_routine_defs[] = {
  {"slsqp",-1,{{-1}},0,(char *)F_FUNC(slsqp,SLSQP),(f2py_init_func)f2py_rout_slsqp_slsqp,doc_f2py_rout_slsqp_slsqp},
  {"openunit",-1,{{-1}},0,(char *)F_FUNC(openunit,OPENUNIT),(f2py_init_func)f2py_rout_slsqp_openunit,doc_f2py_rout_slsqp_openunit},
  {"pyflush",-1,{{-1}},0,(char *)F_FUNC(pyflush,PYFLUSH),(f2py_init_func)f2py_rout_slsqp_pyflush,doc_f2py_rout_slsqp_pyflush},
  {"closeunit",-1,{{-1}},0,(char *)F_FUNC(closeunit,CLOSEUNIT),(f2py_init_func)f2py_rout_slsqp_closeunit,doc_f2py_rout_slsqp_closeunit},

/*eof routine_defs*/
  {NULL}
};

static PyMethodDef f2py_module_methods[] = {

  {NULL,NULL}
};

#if PY_VERSION_HEX >= 0x03000000
static struct PyModuleDef moduledef = {
  PyModuleDef_HEAD_INIT,
  "slsqp",
  NULL,
  -1,
  f2py_module_methods,
  NULL,
  NULL,
  NULL,
  NULL
};
#endif

#if PY_VERSION_HEX >= 0x03000000
#define RETVAL m
PyObject *PyInit_slsqp(void) {
#else
#define RETVAL
PyMODINIT_FUNC initslsqp(void) {
#endif
  int i;
  PyObject *m,*d, *s;
#if PY_VERSION_HEX >= 0x03000000
  m = slsqp_module = PyModule_Create(&moduledef);
#else
  m = slsqp_module = Py_InitModule("slsqp", f2py_module_methods);
#endif
  Py_TYPE(&PyFortran_Type) = &PyType_Type;
  import_array();
  if (PyErr_Occurred())
    {PyErr_SetString(PyExc_ImportError, "can't initialize module slsqp (failed to import numpy)"); return RETVAL;}
  d = PyModule_GetDict(m);
  s = PyString_FromString("$Revision: $");
  PyDict_SetItemString(d, "__version__", s);
#if PY_VERSION_HEX >= 0x03000000
  s = PyUnicode_FromString(
#else
  s = PyString_FromString(
#endif
    "This module 'slsqp' is auto-generated with f2py (version:2).\nFunctions:\n"
"  a = slsqp(m,meq,la,n,x,xl,xu,f,c,g,a,acc,iter,iprint,iout,ifile,mode,w,l_w,jw,l_jw,nfunc,ngrad,slfunc,slgrad,slfunc_extra_args=(),slgrad_extra_args=())\n"
"  ierror = openunit(unitnum,filename,filestatus,fileaction)\n"
"  pyflush(unitnum)\n"
"  closeunit(unitnum)\n"
".");
  PyDict_SetItemString(d, "__doc__", s);
  slsqp_error = PyErr_NewException ("slsqp.error", NULL, NULL);
  Py_DECREF(s);
  for(i=0;f2py_routine_defs[i].name!=NULL;i++)
    PyDict_SetItemString(d, f2py_routine_defs[i].name,PyFortranObject_NewAsAttr(&f2py_routine_defs[i]));




/*eof initf2pywraphooks*/
/*eof initf90modhooks*/

/*eof initcommonhooks*/


#ifdef F2PY_REPORT_ATEXIT
  if (! PyErr_Occurred())
    on_exit(f2py_report_on_exit,(void*)"slsqp");
#endif

  return RETVAL;
}
#ifdef __cplusplus
}
#endif
