name: codestyle-checks
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  black-format:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Black Code Formatter
      uses: lgeiger/black-action@v1.0.1
      with:
          args: ". --check -l 120"
